Feature/#73
woowacourse-teams/2023-trip-draw pull request #141
Opened 2023-08-01 07:11 UTC by beer-2000

### 📌 관련 이슈

- closed #이슈번호

### 📁 작업 설명

- 설명

### 📸 작업화면(선택)

### 💻 미완료 태스크(선택)

- [ ] Task1

2023-08-01 08:07 UTC, greeng00se approved these changes
꼼꼼하게 잘 작성하셨네요! 고생하셨습니다~

2023-08-01 10:15 UTC, Jaeyoung22 requested changes
고생하셨습니다! 간단한 커멘트만 확인해주세요!

2023-08-01 10:15 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/application/PostServiceTest.java
> +    private LoginUser loginUser2;
저번 PR 때 테스트의 변수들을 숫자로 구분하지 말자는 피드백을 받았었는데요, 해당 내용 공유 드립니다!

2023-08-01 10:15 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/application/PostServiceTest.java
> +        LoginUser wrongUser = new LoginUser("상한 통후추");
닉네임에 공백을 허용하지 않아서 참고해주세요!

2023-08-01 11:56 UTC, Combi153 approved these changes
고생하셨습니다! 테스트코드가 꼼꼼해서 읽고 이해하기 편했습니다!
몇 가지 제안 사항 남겨두고 어프루브 하겠습니다

2023-08-01 11:56 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/presentation/controller/PostController.java
> +    }
```suggestion
    public ResponseEntity<PostResponse> read(
            @Auth LoginUser loginUser,
            @PathVariable Long postId
    ) {
        PostResponse response = postService.read(loginUser, postId);
        return ResponseEntity.ok(response);
    }
```
메서드 만들어져 있는 거 쓰면 편할 것 같습니다!

2023-08-01 11:56 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/application/PostServiceTest.java
> +        Member member2 = memberRepository.save(new Member("순후추"));
변수 `member2`를 setUp 메서드 내에서 사용하지 않아서 굳이 초기화할 필요가 없을 것 같습니다! memberRepository.save(new Member("순후추")); 만 해도 괜찮을 것 같아요!

2023-08-01 11:56 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/presentation/controller/PostControllerTest.java
> +    }
URL을 `/posts/{postId}`로 명시하고, 파라메터로 path variable을 설정하면 테스트 코드 읽기가 더욱 편할 것 같습니다!
```suggestion
    @Test
    void 특정_감상을_조회할_때_존재하지_않는_감상_ID이면_예외가_발생한다() {
        // given & expect
        RestAssured.given().log().all()
                .contentType(MediaType.APPLICATION_JSON_VALUE)
                .auth().preemptive().oauth2(통후추_BASE64)
                .when().get("/posts/{postId}", -1L)
                .then().log().all()
                .statusCode(NOT_FOUND.value());
    }
```

2023-08-01 11:56 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/presentation/controller/PostControllerTest.java
> +        // given
주석 제거하면 좋을 것 같습니다~

2023-08-02 01:38 UTC, beer-2000 commented on backend/src/main/java/dev/tripdraw/presentation/controller/PostController.java
> +@RequestMapping("/posts")
하지만 다시 롤백..

2023-08-02 01:38 UTC, beer-2000 commented on backend/src/test/java/dev/tripdraw/presentation/controller/PostControllerTest.java
> +                .contentType(MediaType.APPLICATION_JSON_VALUE)
적용했습니다 감사합니다~

2023-08-02 01:40 UTC, beer-2000 commented on backend/src/test/java/dev/tripdraw/application/PostServiceTest.java
> +    private LoginUser loginUser2;
otherUser로 수정했습니다! 감사합니다~

2023-08-02 01:41 UTC, beer-2000 commented on backend/src/test/java/dev/tripdraw/application/PostServiceTest.java
> +        LoginUser wrongUser = new LoginUser("상한 통후추");
오 수정했습니다 또 놓쳤네용 감사합니다!

2023-08-02 01:44 UTC, beer-2000 commented on backend/src/main/java/dev/tripdraw/presentation/controller/PostController.java
> +    }
다른 컨트롤러 메서드도, 해당 메서드 사용하고 있어서
저도 사용했습니다! 감사합니다~

2023-08-02 01:45 UTC, beer-2000 commented on backend/src/test/java/dev/tripdraw/application/PostServiceTest.java
> +        Member member2 = memberRepository.save(new Member("순후추"));
오 맞네용!! 제거했습니다 감사해요~

2023-08-02 01:51 UTC, beer-2000 commented on backend/src/test/java/dev/tripdraw/presentation/controller/PostControllerTest.java
> +    }
오 너무 좋은데요? 바로 다 반영해버렸습니다

2023-08-02 01:51 UTC, beer-2000 commented on backend/src/test/java/dev/tripdraw/presentation/controller/PostControllerTest.java
> +        // given
매의 눈.. 감사합니다!!!

2023-08-02 03:13 UTC, Jaeyoung22 approved these changes
고생했습니다!

2023-08-02 03:17 UTC, merged