[feat] 서버에 감상 사진 저장 및 URL 반환 기능 구현
woowacourse-teams/2023-trip-draw pull request #145
Opened 2023-08-01 08:17 UTC by Jaeyoung22

### 📌 관련 이슈

- closed #111 

### 📁 작업 설명

- 서버에 감상 사진 저장 기능 구현
- 저장된 사진에 대한 URL 반환 기능 구현

추후 설명 추가 예정

2023-08-01 10:11 UTC, greeng00se requested changes
파일 업로드 기능 구현하느라 고생하셨습니다.
테스트가 많이 어려웠을 것 같아요~
코멘트 작게 남겼습니다~

2023-08-01 10:11 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/application/file/FilePath.java
> +        );
아래에 있는 Map과 함께 static 변수로 추출해보는건 어떨까요?

2023-08-01 10:11 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/application/PostService.java
>  @Transactional
수정 전에 Spring의 Transactional 적용해주면 좋을 것 같아요~

2023-08-01 10:11 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/application/file/FileUploader.java
> +        String filePathWithBase = this.filePath.getPathWithBase(fileType) + id + fileType.extension();
this.filePath를 사용하신 이유가 있을까요?

2023-08-01 10:11 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/domain/post/Post.java
> +    }
setter 느낌이 많이 드는데 해당 메서드명에 대해 어떻게 생각하시나요?

2023-08-01 10:11 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/dto/UrlStringToStringBase64Encoder.java
> +}
dto 아래 해당 클래스가 있는데 어떤 용도로 사용되고 있나요? 다른 좋은 방법은 없을까요?

2023-08-01 10:11 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/exception/file/FileIOExceptionType.java
> +    }
혹시 이 부분에 반환값이 null인 이유가 있나요?

2023-08-01 10:11 UTC, greeng00se commented on backend/src/main/resources/db/migration/V2__addImageUrl.sql
> +alter table post add column image_url varchar(255);
꼼꼼한 설정 👍

2023-08-01 10:11 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/application/file/FileUploaderTest.java
> +        System.out.println(url);
꼼꼼한 테스트 👍 
sout의 경우 제거해도 될 것 같아요~

2023-08-01 10:11 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/application/file/FileUrlMakerTest.java
> +        Assertions.assertThat(url).isEqualTo("ip" + "/통후추/통후추의셀카.jpg");
Assertions와 위에있는 DisplayNameGenerator Static Import 하면 좋을 것 같아요~

2023-08-01 10:21 UTC, beer-2000 requested changes
사진 저장하는 무거운 로직 작성하시느라 고생하셨습니다!
객체지향적이고 가독성 좋은 코드라 쉽게 이해하고 리뷰할 수 있었던 것 같아요.

몇 가지 제안 겸 의견 남겨보았으니 확인 부탁드립니다~

2023-08-01 10:21 UTC, beer-2000 commented on backend/src/main/java/dev/tripdraw/application/file/FilePath.java
> +                FileType.POST_IMAGE, postImagePath
static import하면 어떨지요?

2023-08-01 10:21 UTC, beer-2000 commented on backend/src/main/java/dev/tripdraw/application/file/FilePath.java
> +                FileType.POST_IMAGE, base + postImagePath
static import하면 어떨지요? (2)

2023-08-01 10:21 UTC, beer-2000 commented on backend/src/main/java/dev/tripdraw/application/file/FileUploader.java
> +        String filePathWithBase = this.filePath.getPathWithBase(fileType) + id + fileType.extension();
path를 받는 로직이라면, FilePath에 FileType을 넘겨주고 결과(String)를 받아오는 형식이면 어떨까 싶습니다.
객체지향적 관점에서요!

2023-08-01 10:23 UTC, beer-2000 commented on backend/src/main/java/dev/tripdraw/domain/post/Post.java
> +    }
느낌 아니고 setter잖아요 ㅋㅋㅋㅋㅋㅋㅋ

2023-08-01 10:26 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/application/file/FilePath.java
> +        );
현재 구조상 static 변수로 추출하는 것은 불가능합니다! 

추후에 클래스 구조를 바꾸면 더 효율적인 코드가 가능할 것 같습니다!

2023-08-01 10:28 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/application/PostService.java
>  @Transactional
제가 싼 똥은 아니지만 치워드렸습니다^^~

2023-08-01 10:30 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/application/file/FileUploader.java
> +        String filePathWithBase = this.filePath.getPathWithBase(fileType) + id + fileType.extension();
앗 잘못들어가있었네요!

2023-08-01 10:32 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/domain/post/Post.java
> +    }
추후에 팀과 통일 후 변경하겠습니다~

2023-08-01 10:33 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/exception/file/FileIOExceptionType.java
> +    }
앗 감사합니다!

2023-08-01 10:38 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/dto/trip/TripResponse.java
> +        @Schema(description = "Base64로 인코딩 된 여행 대표 이미지 URL", example = "")
환경변수 설정 후 적용했어야했는데 깜빡했네요! 감사합니다!

2023-08-01 10:40 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/presentation/controller/PostController.java
> +            @RequestPart(value = "file", required = false) MultipartFile file
좋은 방법 추천 감사합니다! 추후에 변경하도록 하겠습니다!

2023-08-01 10:43 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/application/file/FileUploader.java
> +        String filePathWithBase = this.filePath.getPathWithBase(fileType) + id + fileType.extension();
UUID를 이용해서 만드는 것은 파일 이름 (FileName)이라고 생각해서 FilePath에서 분리했습니다! 업로드 할 때만 UUID가 사용되기도 해서 이 부분에 놨는데,
해당 부분도 추후에 논의하도록 하겠습니다!

2023-08-01 10:48 UTC, greeng00se approved these changes
고생하셨습니다 👍

2023-08-01 12:47 UTC, Combi153 requested changes
정말 고생하셨습니다. 저도 열심히 공부해야겠네요! 자극이 됩니다.
다른 분들이 리뷰 많이 남겨주셔서 조금만 남겼습니다.
base64 encoding 에 관한 궁금증 때문에 Request Changes 로 하겠습니다!

2023-08-01 12:47 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/dto/UrlStringToStringBase64Encoder.java
> +    }
dto 관련 로직이긴 하지만, 테스트코드를 작성하면 좋지 않을까요?

보다 근본적으로 궁금증이 있는데 이미지 url 을 base64로 인코딩해서 반환하는 이유가 있나요?

2023-08-01 12:47 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/dto/trip/TripResponse.java
> +        @Schema(description = "Base64로 인코딩 된 여행 대표 이미지 URL", example = "")
example을 비워둔 이유가 있으신가요? 뭐라도 하나 넣어주신다면 클라가 좋아할 듯 합니다.

2023-08-01 17:11 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/dto/trip/TripResponse.java
> +        @Schema(description = "Base64로 인코딩 된 여행 대표 이미지 URL", example = "")
빠트렸네요ㅠㅠ 넣었습니다! 감사합니다!

2023-08-01 17:19 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/dto/UrlStringToStringBase64Encoder.java
> +    }
좋습니다! 저도 테스트코드를 작성해야한다고 생각해요!
다만 인코딩을 하지 않기로 합의를 해서 제거하도록 하겠습니다~!

이미지 url이라기보다, url 자체를 base64로 인코딩해서 반환하는 이유는 쿼리 파라미터 등을 안전하게 전송하기 위해서로 알고 있습니다!

2023-08-02 01:00 UTC, Combi153 approved these changes
커멘트 확인했고 어프루브 하겠습니다
고생 많으셨습니다~

2023-08-02 01:01 UTC, beer-2000 commented on backend/src/test/java/dev/tripdraw/presentation/controller/PostControllerTest.java
> +                .multiPart("dto", postAndPointCreateRequest, MediaType.APPLICATION_JSON_VALUE)
통일하는 것은 좋은데, 어떤 형식이 들어와야 하는지 감이 오지 않아서요.
예를 들어, 도메인 형식이라면 `domain.example` 형식을 사용할 수 있고, JPG 파일이 저장된 S3 주소라면 `https://s3.ap-northeast-2.amazonaws.com/bucket-name/example.jpg` 이렇게 사용할 수 있을 것 같아요.
혹시 저 자리에 dto가 들어가는데 제 이해가 부족해서 그런 것일까요?
어떤 형태가 들어가는지 잘 모르겠어서 질문 드립니다!

2023-08-02 01:35 UTC, beer-2000 approved these changes
반영해주신 것 확인하고 approve 남기겠습니다.
슬랙에서 말씀주셨듯, 추후에 반영할 부분들 표시해두신 것도 확인했습니다.

다만 아래 코멘트에 대해서는 의견을 달아주시거나 코드가 변경되지 않은 것 같아 리마인드 차 링크 남깁니다.
- https://github.com/woowacourse-teams/2023-trip-draw/pull/145#discussion_r1280317214

그리고 아래 코멘트는 새로 남기게 되어 링크 남깁니다.
- https://github.com/woowacourse-teams/2023-trip-draw/pull/145#discussion_r1281278616

확인 부탁드려요.
거대한 기능 개발하시느라 고생하셨습니다!

2023-08-02 02:02 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/presentation/controller/PostControllerTest.java
> +                .multiPart("dto", postAndPointCreateRequest, MediaType.APPLICATION_JSON_VALUE)
아 이건 multipart/form-data에서 json property 지정해주듯이 넣어주는 값입니다! 
그래서 dto라는 이름으로 정했어요~

2023-08-02 02:03 UTC, merged