[feat] 여행 삭제 기능 추가 및 회원 탈퇴 기능 수정 (#255)
woowacourse-teams/2023-trip-draw pull request #270
Opened 2023-08-10 17:58 UTC by Combi153

### 📌 관련 이슈

- closed #255 

### 📁 작업 설명

- 여행 삭제 기능 추가

### 참고
- 회원 삭제(탈퇴)를 soft delete 에서 hard delete 로 수정했습니다.
- 여행 삭제를 hard delete로 구현했습니다.
- 위치 정보 삭제 역시 hard delete 고려 중입니다.
- 위치 정보 삭제 후 삭제된 위치가 조회되는 것을 수정했습니다.

2023-08-10 23:54 UTC, greeng00se requested changes
고생하셨습니다~ 👍 
남긴 코멘트 확인 부탁드립니다~

2023-08-10 23:54 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/application/MemberService.java
> +                         PostRepository postRepository, AuthTokenManager authTokenManager) {
개행을 적용하면 컨벤션을 맞출 수 있을 것 같습니다~

2023-08-10 23:54 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/application/MemberService.java
> +        memberRepository.deleteById(memberId);
code를 ArgumentResolver에서 처리해서 memberId로 받는 방법도 있을 것 같습니다~ (헤더, Param 둘다 사용가능하도록)
어차피 파라미터에는 한 군데만 사용해서 지금 형태도 좋습니다 👍

2023-08-10 23:54 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/application/TripService.java
> +    }
해당 부분은 자신의 여행인지에 대한 검증 과정이 필요할 것 같아요 LoginUser를 받아 사용하지 않고 있습니다~

2023-08-10 23:54 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/domain/trip/Route.java
> +    @OneToMany(fetch = LAZY, cascade = ALL)
PERSIST와 REMOVE만 적용해보는건 어떨까요?

2023-08-11 01:20 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/application/TripService.java
> +    }
넵 추가하겠습니다!

2023-08-11 01:21 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/application/MemberService.java
> +                         PostRepository postRepository, AuthTokenManager authTokenManager) {
아 이걸 못봤네요~~ 맞추겠습니다

2023-08-11 01:21 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/domain/trip/Route.java
> +    @OneToMany(fetch = LAZY, cascade = ALL)
와 좋은 거 알아갑니다!

2023-08-11 01:30 UTC, beer-2000 approved these changes
고생하셨습니다!
허브 코멘트 외에 필요한 수정사항을 발견 못해서 approve 남깁니다.
(추가로, 스웨거 관련 자잘한 변경사항 하나 DM으로 요청드릴게요🥲)

2023-08-11 02:58 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/application/MemberService.java
> +        memberRepository.deleteById(memberId);
하나의 argumentResolver에서 header, queryString 를 모두 관리하는 건가요?

2023-08-11 03:49 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/application/MemberService.java
> +        memberRepository.deleteById(memberId);
넵 쿼리에 붙여도 동작하도록 할 수 있을 것 같아서 남겨봅니당

2023-08-11 07:28 UTC, Jaeyoung22 approved these changes
고생하셨습니다!

2023-08-11 07:31 UTC, merged