[feat] 회원 닉네임 등록 시 중복 검증 추가 (#278)
woowacourse-teams/2023-trip-draw pull request #279
Opened 2023-08-11 12:28 UTC by Combi153

### 📌 관련 이슈

- closed #278 

### 📁 작업 설명

- 회원 닉네임 등록 시 중복 검증을 추가했습니다.

### 참고
두 가지 선택지를 고려했습니다.

1. 전체 회원의 이름 목록을 불러와서 Member.changeName() 메서드의 파라미터로 전달한 후, Member.changeName() 메서드 내에서 검증하는 방법
2. MemberRepository.existsByNickname()  메서드로 존재 여부만 확인한 후 검증하는 방법

이 중에 첫번째 방법은 회원의 수가 많아질수록 "데이터 조회 시간" + "중복 검사 시간"이 늘어날 것으로 예상했습니다. 따라서 두 번째 방법을 택했습니다. 자세한 내용은 아래와 같습니다.

memberRepository에 `existsByNickname` 메서드를 추가했습니다.
```java
public interface MemberRepository extends JpaRepository<Member, Long> {

    boolean existsByNickname(String nickname);
}
```

authService에서 이 메서드를 활용합니다.

```java
@Transactional
@Service
public class AuthService {

    // (...)
    public OauthResponse register(RegisterRequest registerRequest) {
        OauthClient oauthClient = oauthClientProvider.provide(registerRequest.oauthType());
        OauthInfo oauthInfo = oauthClient.requestOauthInfo(registerRequest.oauthToken());

        Member member = memberRepository.findByOauthIdAndOauthType(oauthInfo.oauthId(), oauthInfo.oauthType())
                .orElseThrow(() -> new MemberException(MEMBER_NOT_FOUND));

        String nickname = registerRequest.nickname();
        validateNicknameDuplication(nickname);
        member.changeNickname(nickname);

        String accessToken = authTokenManager.generate(member.id());
        return new OauthResponse(accessToken);
    }

    private void validateNicknameDuplication(String nickname) {
        if (memberRepository.existsByNickname(nickname)) {
            throw new MemberException(NICKNAME_CONFLICT);
        }
    }
}
```

더 예쁜 방법 있으면 알려주세요!

2023-08-11 14:53 UTC, greeng00se approved these changes
고생하셨습니다 👍 

두 가지 선택지를 고려해주신 부분 너무 좋은 것 같습니다!
사용해주신 existsBy에 대한 [재밌는 글](https://jojoldu.tistory.com/516) 하나 남기고 갑니다~

2023-08-11 16:31 UTC, beer-2000 approved these changes
꼼꼼한 테스트와 구현이 좋네요!
자잘한 제안 외에, 수정 바라는 점은 없어
approve 하겠습니다~

고생하셨습니다!

2023-08-11 16:31 UTC, beer-2000 commented on backend/src/main/java/dev/tripdraw/application/AuthService.java
> +import static dev.tripdraw.exception.member.MemberExceptionType.NICKNAME_CONFLICT;
```suggestion
import static dev.tripdraw.exception.member.MemberExceptionType.DUPLICATE_NICKNAME;
```

어떨지요?
CONFLICT라는 뜻이 중복이라는 뜻으로 쓰이고 있나요? 제가 영어가 약해서..

2023-08-11 16:31 UTC, beer-2000 commented on backend/src/main/java/dev/tripdraw/application/oauth/AuthTokenManager.java
> +    private final Long expirationTime;
매의눈 좋습니다!!

2023-08-12 01:04 UTC, Jaeyoung22 requested changes
고생하셨네요..! 테스트에 사소한 RC만 확인해주세요!

2023-08-12 01:04 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/application/AuthService.java
> +        validateNicknameDuplication(nickname);
체인저가 제시해준 첫번째 메서드 명 아주 좋네요!

2023-08-12 01:04 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/domain/member/MemberRepositoryTest.java
> +    @CsvSource({"통후추, true", "순후추, false"})
👍

2023-08-12 01:04 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/presentation/controller/AuthControllerTest.java
> +        Member member = memberRepository.save(new Member("중복된 닉네임", "kakaoId", KAKAO));
닉네임에 중복허용 안됩니다..!

2023-08-12 07:48 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/application/AuthService.java
> +import static dev.tripdraw.exception.member.MemberExceptionType.NICKNAME_CONFLICT;
이름 좋네요!

2023-08-12 07:48 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/application/oauth/AuthTokenManager.java
> +    private final Long expirationTime;
감사합니다~

2023-08-12 07:49 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/application/AuthService.java
> +        validateNicknameDuplication(nickname);
전자로 바꾸겠습니다!

2023-08-12 07:49 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/application/AuthServiceTest.java
> +    void 신규_회원의_닉네임을_등록할_때_이미_존재하는_닉네임이면_예외가_발생한다() {
ㅋㅋㅋ좋스빈다

2023-08-12 07:50 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/presentation/controller/AuthControllerTest.java
> +        Member member = memberRepository.save(new Member("중복된 닉네임", "kakaoId", KAKAO));
공백 허용이 안 된다는 의미겠죠?

2023-08-12 08:29 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/presentation/controller/AuthControllerTest.java
> +        Member member = memberRepository.save(new Member("중복된 닉네임", "kakaoId", KAKAO));
@NoWhiteSpace 적용까지 했습니다!

2023-08-12 10:06 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/presentation/controller/AuthControllerTest.java
> +        Member member = memberRepository.save(new Member("중복된 닉네임", "kakaoId", KAKAO));
개떡찰떡 굳

2023-08-12 10:06 UTC, Jaeyoung22 approved these changes
고생하셨습니다!

2023-08-12 14:55 UTC, merged