[refactor] repository 호출 시 중복 제거 (#224)
woowacourse-teams/2023-trip-draw pull request #290
Opened 2023-08-12 14:54 UTC by Combi153

### 📌 관련 이슈

- closed #224 

### 📁 작업 설명

- 허브가 만들어둔 이슈 처리하기
- repository getById 메서드를 만들어 사용하도록 리팩터링했습니다.

2023-08-13 00:32 UTC, Jaeyoung22 requested changes
고생하셨습니다~ 오탈자 하나만 수정해주세요!

2023-08-13 00:32 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/domain/post/PostRepository.java
> +                .orElseThrow(() -> new PostException(POST_NOT_FOUNT));
아직 허브 PR이 머지가 안돼서 이렇군요...

2023-08-13 11:06 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/domain/post/PostRepository.java
> +                .orElseThrow(() -> new PostException(POST_NOT_FOUNT));
이거 허브 것 머지되면, rebase로 수정할게요!

2023-08-13 14:23 UTC, greeng00se approved these changes
고생하셨습니다~ 제 PR이랑 충돌 가능성이 높으니 후에 머지해주시면 감사하겠습니다 👍

2023-08-16 01:38 UTC, beer-2000 approved these changes
고생하셨습니다~~

2023-08-16 01:38 UTC, beer-2000 commented on backend/src/test/java/dev/tripdraw/domain/member/MemberRepositoryTest.java
> +    void 회원_ID로_회원을_조회할_때_존재하지_않는_경우_예외를_발생시킨다() {
테스트까지 좋네용!

2023-08-31 07:33 UTC, merged