[feat] AccessToken 갱신 기능을 구현한다 (#292)
woowacourse-teams/2023-trip-draw pull request #303
Opened 2023-08-14 09:01 UTC by Jaeyoung22

### 📌 관련 이슈

- closed #292 

### 📁 작업 설명

## 테스트 코드 메서드 내에서 시간을 흐르게 하는 방법

Access Token을 갱신하는 기능을 구현했습니다.

해당 기능은 다음과 같은 로직으로 동작합니다.

1. 토큰이 유효한지를 확인함 -> 유효하지 않다면 예외를 반환 -> 클라에서 다시 로그인 요청
2. 토큰이 만료되었는지를 확인함 -> 만료되었다면 예외를 반환 -> 클라에서 다시 로그인 요청
3. 토큰의 소유자를 확인함 -> 확인이 된다면 새로운 토큰을 발급해 줌

간단한 로직이지만, 테스트 시에 문제가 되는 부분이 있었습니다.
1. 만료된 토큰을 만드는 것
2. 토큰의 생성 이후, 다시 토큰을 재발급하려면 "1초라도" 시간이 지나야한다는 것

해당 문제를 해결하기 위해 처음에는 Thread.sleep() 메서드를 사용했습니다.

<img width="827" alt="image" src="https://github.com/woowacourse-teams/2023-trip-draw/assets/89302528/f80ae964-588f-466a-9874-0086a7dc097a">

그러나 해당 방법으로는 테스트를 실행할 때 실제로 지정한 시간만큼 쓰레드가 멈추게 됩니다.

적절하지 않다고 판단하여 방법을 찾아봤습니다.

# 1. Clock 클래스 사용
Java 내장 라이브러리의 Clock 클래스를 사용하고,
AccessTokenManager에서 expirationTime을 설정할 때 Date 클래스가 아닌, 이 Clock 클래스를 이용하여 사용을 하면
테스트 시에 mocking이 가능해지는 장점이 있었습니다.
하지만 이는 비즈니스 로직을 변경해야하는 단점이 존재했습니다.

# 2. Spring AOP 사용
Spring AOP에서 제공하는 @Aspect 어노테이션을 이용하여, 특정 메서드와 관련하여 실행 전, 실행 후, 혹은 메서드를 감싸서 실행되는 다른 메서드를 설정할 수 있습니다.

그래서 AuthService 클래스의 login() 메서드와, refresh() 메서드를 @Around 어노테이션을 이용하여 시간을 조정하여 토큰을 발급하도록 했습니다.

```java
@Aspect
@Component
public class TimeTravelToFutureWhenRefreshAspect {

    // ...

    @Around("execution(* dev.tripdraw.application.AuthService.refresh(..))")
    public Object manipulateTime(ProceedingJoinPoint joinPoint) throws Throwable {
        if (customTime != null) {
            AccessTokenRefreshRequest request = (AccessTokenRefreshRequest) joinPoint.getArgs()[0];
            Long memberId = authTokenManager.extractMemberId(request.accessToken());

            Instant manipulatedExpirationTime = Instant.now().plusSeconds(60);
            String newAccessToken = jwtTokenProvider.generate(
                    String.valueOf(memberId),
                    Date.from(manipulatedExpirationTime)
            );

            OauthResponse manipulatedResponse = new OauthResponse(newAccessToken);

            Object originalResponse = joinPoint.proceed();
            if (originalResponse instanceof OauthResponse) {
                return manipulatedResponse;
            } else {
                return originalResponse;
            }
        }

        return joinPoint.proceed();
    }
}
```

```java
@Aspect
@Component
public class TimeTravelToPastWhenLogInAspect {

    // ...

    @Around("execution(* dev.tripdraw.application.AuthService.login(..))")
    public Object manipulateTime(ProceedingJoinPoint joinPoint) throws Throwable {
        if (customTime != null) {
            OauthRequest request = (OauthRequest) joinPoint.getArgs()[0];
            OauthClient oauthClient = oauthClientProvider.provide(request.oauthType());
            OauthInfo oauthInfo = oauthClient.requestOauthInfo(request.oauthToken());

            Member member = memberRepository.findByOauthIdAndOauthType(oauthInfo.oauthId(), oauthInfo.oauthType())
                    .orElseThrow(() -> new MemberException(MEMBER_NOT_FOUND));

            Instant manipulatedExpirationTime = Instant.EPOCH;
            String newAccessToken = jwtTokenProvider.generate(
                    String.valueOf(member.id()),
                    Date.from(manipulatedExpirationTime)
            );

            OauthResponse manipulatedResponse = new OauthResponse(newAccessToken);

            Object originalResponse = joinPoint.proceed();
            if (originalResponse instanceof OauthResponse) {
                return manipulatedResponse;
            } else {
                return originalResponse;
            }
        }

        return joinPoint.proceed();
    }
}
```

위의 두 클래스를 통해 AOP로 각 메서드의 실행 시에 시간을 조작하여 그 시간에 해당하는 토큰을 발급하도록 했습니다.

```java
@SuppressWarnings("NonAsciiCharacters")
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
@ComponentScan(basePackages = "dev.tripdraw.aspect")
class AuthControllerTest extends ControllerTest {
    
    // ...

        @Test
        void 액세스_토큰이_유효하면_갱신한다() throws InterruptedException {
            
            // ...
            
            // when
            timeTravelToFutureWhenRefreshAspect.timeTravelTo("A few moments later...");
            ExtractableResponse<Response> refreshResponse = RestAssured.given().log().all()
                    .contentType(APPLICATION_JSON_VALUE)
                    .body(accessTokenRefreshRequest)
                    .when().get("/oauth/refresh")
                    .then().log().all()
                    .extract();
            OauthResponse newOauthResponse = refreshResponse.as(OauthResponse.class);
            String refreshedAccessToken = newOauthResponse.accessToken();

            // ...
            }
}
```

AuthControlleTest, AuthServiceTest 두 곳에서 위와 같은 방법으로 시간을 조작하여 테스트를 진행했습니다.

해당 방법을 사용하는 경우,
테스트 코드 내에서 시간이 조작되었음을 명확하게 알 수 없다는 단점이 있습니다.

## 선택
thread를 멈추게 하는 방법은 추후 리프레쉬 토큰을 도입할 때, 실제로 만료된 토큰을 사용해야 하기 때문에 
추후 테스트를 작성할 때 우리가 지정한 만료기간만큼 실제로 thread가 멈춰있어야 하는 문제가 생깁니다.

Clock 클래스를 사용할 수 있으나, 이번에는 비즈니스 로직을 변경하지 않으려고 선택하지 않았습니다.

그래서 Spring AOP를 사용하여 테스트를 진행했습니다.

## 단점 보완
위에 언급했듯이, Spring AOP를 사용하여 테스트를 작성하니 각 메서드에서 시간이 조작되었음을 명확히 알 수 있는 방법이 없었습니다.
그래서 아래와 같은 방법으로 조금이나마 보완했습니다.

각 aspect에서 로직을 진행할 때 customTime이 null이 아닌 경우, 로직이 실행됩니다.
즉, aspect.setCustomTime()의 인자로는 사실 아무 String 값이나 들어가도 실행이 됩니다.

그래서 시간 조정이 필요한 부분에 aspect의 customTime을 변경하고, 그 인자로 시간이 흘렀음을 알려주는 문구를 넣어서 단점을 보완하려 했습니다.

2023-08-14 13:04 UTC, Combi153 requested changes
aop 공부 쉽지 않았을텐데 고생하셨습니다.
리팩터링 제안 드립니다!

2023-08-14 13:04 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/application/AuthServiceTest.java
> +    }
물론 Test 에서 JwtTokenProvider를 의존하는 것이 꺼려질 수 있습니다.

그러나 현재 코드는 아래와 같은 단점을 갖고 있다 생각합니다.

- 읽기 어렵다
- aop로 인해 유지보수가 어렵다(제가 aop가 낯설어 유지보수가 어려울 것이라 예상합니다)
- 테스트를 위한 aop 도입이 과도하다

이런 점에서 미루어볼 때 JwtTokenProvider를 의존하는 것이 더 괜찮은 선택으로 다가옵니다.

Test 에서 JwtTokenProvider를 의존하는 것이 꺼려진다면, TestJwtTokenProvider를 테스트용으로 만들어서 사용하면 어떨까 합니다.

2023-08-14 13:04 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/presentation/controller/AuthControllerTest.java
> +            // given
여기도 마찬가지로 JwtTokenProvider를 의존해서 사용하면 어떨까요?

2023-08-14 13:26 UTC, greeng00se requested changes
쉬는 날인데 코딩하느라 고생하셨습니다. 👍 
코멘트 하나 남겼습니다 확인해주세용

2023-08-14 13:26 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/application/AuthServiceTest.java
> +    }
aop 이용해서 테스트 하신다고 고생하셨습니다 👍 
SpringBootTest라 JwtTokenProvider를 `@Autowired`하여 사용해보는 것도 좋을 것 같습니다 😄 
후추가 말해주신 단점과 더불어서 단일 메서드 테스트가 각각의 aspect 클래스에 의존하는 부분, 또한 aop를 횡단 관심사를 해결하기 위함이 아닌, 단순히 메서드를 테스트 통과시키기 위해 사용하는 부분이 문제가 될 수 있을 것 같습니다.

2023-08-15 09:55 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/application/AuthServiceTest.java
> +    }
현재 각 Aspect에서 일어나는 로직이 후추가 제시해 준 방법과 크게 다르지 않습니다. 
조작된 시간으로 JwtTokenProvider를 이용하여 토큰을 발급 받는 건데, 
각 aspect의 manipulateTime() 메서드 내부 로직은 시간을 조작하는 대상 메서드의 로직과 동일합니다.
그러므로 후추와 허브가 제시해 준 JwtTokenProvider를 의존하여 테스트를 하는 방법과 다를 바가 없습니다.
그럼에도 Spring AOP를 도입하여 테스트를 작성한 이유는 아래와 같습니다.
후추와 허브의 의견에 다시 커멘트를 다는 식으로 얘기해보겠습니다.

그 전에, 후추가 처음 제시해준 `토큰이_유효하면_액세스_토큰을_갱신한다()`의 테스트는 통과하지 않습니다.
이전에 발급받은 토큰과 새로 갱신한 토큰이 new Date().getTime()의 동일한 시간을 참조하기 때문입니다.
이를 해결하기 위해서는 이전에 발급받은 토큰의 시간을 과거로 조정하는 방법이 있겠습니다.

---

### 1. 읽기 어렵다
-> 저는 이 부분이 PR에 길게 적은 커멘트 하단에서 제시한 방법으로 해결이 되었다고 생각합니다.
현재, AuthControllerTest와 AuthServiceTest 모두 aspect를 이용한 timeTravel() 메서드 한 줄만 추가되어있습니다.
후추가 제시해준 코드와 비교해보겠습니다.

```java
@Test
    void 액세스_토큰_갱신_시에_만료된_토큰이면_예외를_반환한다() {
        // given
        timeTravelToPastWhenLogInAspect.timeTravelTo("호랑이 담배 피던 시절...");
        memberRepository.save(new Member("통후추", "kakaoId", KAKAO));
        OauthResponse oauthResponse = authService.login(new OauthRequest(KAKAO, "oauth.kakao.token"));
        String expiredToken = oauthResponse.accessToken();
        AccessTokenRefreshRequest expiredAccessTokenRefreshRequest = new AccessTokenRefreshRequest(expiredToken);
```

```java
@Test
    void 액세스_토큰_갱신_시에_만료된_토큰이면_예외를_반환한다() {
        // given
        Member member = memberRepository.save(new Member("통후추", "kakaoId", KAKAO));
        String memberId = String.valueOf(member.id());

        Date expiredAt = Date.from(Instant.now().minusSeconds(1));
        String expiredToken = jwtTokenProvider.generate(memberId, expiredAt);
        AccessTokenRefreshRequest request = new AccessTokenRefreshRequest(expiredToken);
```
AOP를 이용한 위의 코드는 timeTravelToPastWhenLogin, timeTravelTo("호랑이 담배 피던 시절...") 등의 네이밍으로 로그인 시점이 과거임을 명시하고 있다고 생각합니다.
허나 아래의 코드는 Date expiredAt = Date.from(Instant.now().minusSeconds(1)); 이라는 한 줄로
'아, 지금보다 1초 전으로 만료 기간을 잡았구나. 그러면 이미 만료가 된 토큰이구나'라고 생각을 한 번 더 해야하는 비용이 들어갑니다.
그러므로 AOP를 이용한 방법이 읽기 어렵다는 의견은 동의하기가 쉽지 않습니다.

---

### 2. 테스트를 위한 AOP 도입이 과도하다, aop를 횡단 관심사를 해결하기 위함이 아닌, 단순히 메서드를 테스트 통과시키기 위해 사용하는 부분이 문제이다.
-> 현재도 AuthContorllerTest와, AuthServiceTest 두 군데에서 `시간을 과거나 미래로 돌려야 한다`라는 횡단 관심사가 생겼습니다. 저는 Test 패키지 내에서의 횡단 관심사를 해결하기 위해서 Aspect 클래스들을 사용했습니다. 그러므로 과도하다거나, 메서드를 테스트 통과시키기 위해 사용했다는 말에 동의하기 쉽지 않습니다.

---


### 3. 단일 메서드 테스트가 각각의 aspect 클래스에 의존한다
-> 이 부분은 잘 이해를 하지 못한 것 같은데, JwtTokenProvider에 의존하는 것과 어떤 차이가 있는지 잘 모르겠습니다. 다시 한 번 얘기해주시면 고맙겠습니다.

---

낯선 방법이라 받아들이는 데에 어려움이나 거부감이 있을 수 있겠지만 열린 자세로 논의해보기를 제안드립니다.
이후 인수테스트를 작성할 때에도 JwtTokenProvider을 꺼내와서 조작된 토큰을 건네는 것 보다,
'`이전`에 발급받은 토큰을 갱신한다'라는 인수 조건에서 시간을 조작하는 것이 더욱 인수 테스트 등의 의미에 적합할 것으로 생각됩니다.
커멘트 다시 부탁합니다.

2023-08-15 13:08 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/application/AuthServiceTest.java
> +    }
저는 일단 approve 하겠습니다.   
추가적으로 AOP 기술을 사용하고 싶으시다면 다른 부분에 적용하는 것을 제안드립니다 🙂  
아래 코멘트는 단순히 논의하기 위한 코멘트로 확인해주시면 감사하겠습니다.

### 1. 현재 각 Aspect에서 일어나는 로직이 후추가 제시해 준 방법과 크게 다르지 않습니다.

→ 후추가 제시한 방법이랑 크게 다르지 않다면 간단하게 문제를 해결할 수 있는 후추의 방법이  더 설득력 있어 보입니다.

후추가 제시해준 테스트가 통과하지 않는다고 하셨는데, 조금만 변형하면 문제없이 동작합니다. 

`토큰이 유효하다면 토큰을 갱신한다`를 테스트하기 위해서는 아래와 같이 아직 유효기간이 남아있는 토큰을 생성하여 테스트하는 것으로 충분해보입니다 👍 

```yaml
Member member = memberRepository.save(new Member("통후추", "kakaoId", KAKAO));
String validToken = jwtTokenProvider.generate(
        member.id().toString(),
        Date.from(Instant.now().plusSeconds(1000))
);
AccessTokenRefreshRequest accessTokenRefreshRequest = new AccessTokenRefreshRequest(validToken);
```

### 2. 읽기 어렵다

코드가 읽기 편하다는 것은 이해하기 쉽다. 라고 생각해주시면 될 것 같습니다. 😄

`timeTravelToPastWhenLogin, timeTravelTo("호랑이 담배 피던 시절...") 등의 네이밍으로 로그인 시점이 과거임을 명시하고 있다고 생각합니다.` 와 같은 부분은 다른 사람이 보기에는 이해하기 어려운 코드가 될 수 있습니다. 네이밍을 잘 지어주셨지만 코드를 이해하기 위해서는 aop를 적용하기 위한 aspect 클래스 두 개를 더 봐야합니다.  

Aspect 클래스를 이해하기 위해 AOP에 대한 기본적인 이해, 포인트컷 표현식, 조인 포인트와 같은 개념을 알아야 합니다.

설명을 잘 남겨주셨지만 아래와 같이 초기화 하는 과정이 왜 이루어져야하는지 이해가 필요할 것 같습니다.

timeTravelToPastWhenLogInAspect.timeTravelTo(null);
timeTravelToFutureWhenRefreshAspect.timeTravelTo(null);

### 3. 횡단 관심사 해결

시간을 과거로 돌려야 한다는 만료된 토큰을 발급하는 것으로, 시간을 미래로 돌려야 한다는 유효한 토큰을 발급하는 것으로 충분히 해결할 수 있을 것 같습니다.

Test 패키지 내에서의 횡단 관심사를 해결하기 위해 AOP를 사용했다고 하셨는데, 따라서 테스트를 위한 코드가 추가된 것이라고 생각합니다.

### 4. JwtTokenProvider를 의존하는 것의 차이

간단하게 말씀드리자면 JwtTokenProvider는 서비스에서 사용되는 코드를 재사용한 것이고 AOP는 테스트를 위해서 만들어진 것입니다.

JwtTokenProvider를 의존하는 것은 결합도가 증가한다고 볼 수 없습니다. 왜냐하면 이미 우리의 회원가입이나 로그인 로직 자체가 해당 JwtTokenProvider를 사용하여 토큰을 발급하기 때문입니다.

하지만 AOP 클래스를 추가해서 테스트 용도로만 사용되는 것은 기존 코드 이외에 추가적으로 클래스를 만들어서 사용하는 것이니 결합도가 증가합니다.

### 추가적인 코멘트

현재 테스트에서 AOP가 다른 테스트도 영향을 받고 있는 부분이 문제가 될 수 있을 것 같습니다. 이 부분을 해결하기 위해 `customTime` 변수를 사용 하셨지만, 저는 이 부분에서 이해하기 조금 어려웠습니다. 

테스트 대상은 AuthService 입니다. 테스트 코드를 보면 AOP가 적용된 AuthService를 테스트 하는 것과 다름이 없다고 느껴집니다.

인수테스트를 작성할 때에도 JwtTokenProvider을 꺼내와서 조작된 토큰을 건네는 것 보다,이전에 발급받은 토큰을 갱신한다'라는 인수 조건에서 시간을 조작하는 것이 더욱 인수 테스트 등의 의미에 적합할 것으로 생각됩니다. → 단순하게 토큰을 발급해주는 fixture를 사용하는 것이 좋아보입니다.

2023-08-15 13:32 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/application/AuthServiceTest.java
> +    }
1. 
`유효기간이 남아있는 토큰`이 중요한 것이 아니라,
`유효기간이 남아있지만 **새롭게 갱신되는 토큰보다 이전에 생성된 토큰**`이 중요합니다..!
물론 JwtTokenManager의 generate() 메서드에, 인자로 new Date("충분히 이전").plus("현재시간을 포함할 수 있는 추가 시간")으로 생성하여 해결할 수 있습니다. -> 다만 이 방법이 aop를 이용한 방법보다 이해가 빨리 된다거나 직관적이라고 생각되지가 않습니다.

2.
간단한 방법으로 해결할 수 있는데 추가적인 개념을 학습해야하는 것에 대한 비용이 든다고 이해하면 될까요? 그렇다면 저는 더더욱 AOP를 사용하는 게 어떨까 생각이 듭니다! 프로젝트의 성격적인 부분도 있고, 같은 방법이라면 새로운 걸 적용해보면서 학습하는 건 어떨까요?
그런데, 말씀하신대로 null로 초기화 하는 로직이 필요한 이유는 설명이 있어야 한다는 것에 동의합니다...

3. 
테스트를 위한 코드는 테스트 내부에서 추가될 수 있다고 생각합니다. 픽스쳐나 TestKakaoClient 등이 그 예시라고 이해하고 있는데 성격이 다른 부분이라고 이해하고 계신걸까요?
테스트를 더 이해하기 쉽고 유려하게 수행하기 위해서 테스트 패키지 내에서 테스트를 위한 코드가 생성되는 것이 어떤 점이 문제인지 아직 잘 모르겠습니다..! 프로덕션 코드에 변경이 생기지 않으니까요..!

4. 
해당 부분은 저도 고려를 했는데요, 
우선 각 테스트의 타겟이 되는 메서드에는 aop가 적용되지 않아야하는 것이 맞는 것 같습니다.
그래서 refresh시에 시간을 미래로 보내는 것은 부적절하다고 생각이 드네요..!
다만 login의 시점을 과거로 보내는 것은 refresh() 메서드를 테스트할 때 문제가 되지 않는다고 생각이 듭니다.
+
각 Aspect 내의 manipulateTime()의 대상이 되는 서비스와 도메인의 로직과 완전히 같습니다.
물론 이 부분에 대해서 설명이 있어야겠지만 그래서 aop가 적용된 service를 테스트하는 것이라고 생각되지는 않았습니다.

2023-08-15 13:55 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/application/AuthServiceTest.java
> +    }
### 1.

새롭게 갱신되는 토큰보다 이전에 생성된 토큰보다, 이 부분은 갱신에 초점을 두는 것이 맞다고 생각됩니다.  
`명시적으로 단순하게 1분 남아있는 토큰을 발급하는 것` vs `aop를 이용하여 1분 남아있는 토큰을 발급하는 것을 숨기는 것` 아무리 생각해봐도테스트 메서드에서 토큰을 생성하고 변수명으로 표현해주는 것이 더 직관적이라고 생각됩니다.

### 2.

팀 차원에서의 학습비용은 매우 중요한 부분이라고 생각합니다. 또한 기술 도입에 코드의 유지보수성도 고려해볼 수 있을 것 같습니다.  
-> 학습 비용을 고려해서 AOP에 대한 정리글을 작성하여 공유하는 방법도 있을 것 같습니다.
프로젝트의 성격과 상관없이 기술의 적용은 근거가 필요하다고 생각합니다.   
솔직히 말씀드리자면 단순 학습 목적이라도 해당 방법을 추천드리지는 않습니다.  
기술의 학습이 목적이라면 로깅에 AOP를 적용하는 것을 적극 추천드립니다.

### 3.

Fixture, Fake와는 성격이 다르다고 생각합니다.  
현재 AOP를 적용하여서 AuthService 자체가 stub처럼 동작하고 있습니다.  
Mockito를 사용해서 AuthService.refresh가 새로운 토큰을 발급하도록 하는 것과 다름이 없습니다.  
의존 구성 요소를 위해 사용하는 클래스와 테스트 대상에 영향을 주는 클래스의 차이라고 생각해볼 수 있을 것 같습니다.

저는 일단 approve 했으니, 다른 팀원들을 설득해보시기 바랍니다 👍

2023-08-16 07:11 UTC, beer-2000 requested changes
리뷰가 늦어 죄송합니다.

별도의 코멘트는 없고,
세 분이서 나누신 대화를 읽어보면서 제가 생각한 바를 적어보겠습니다.

AOP로 시점을 변경하여, 시간의 흐름 제어를 테스트 로직에서 분리시킨 방식이 창의적이라는 생각이 듭니다.

하지만 AOP를 사용하지 않고도 어렵지 않게 구현할 수 있는 테스트에 AOP를 사용하는 것이 필수적인가 라는 의문이 듭니다.
AOP는 학습이 필수적인 좋은 키워드이지만, 로깅이나 인증과 같은 일반적인 경우가 아닌
테스트 관심사 분리에 사용하는 것을 위해 학습을 하기에는 조금 부담이 됩니다.
당장 코드를 작성하다가, AOP 코드가 포함된 테스트가 실패하는 경우 스스로 해결할 수 있을지 의문이 듭니다.

이런 이유로, AOP를 사용하지 않은 방식으로 해결하는 것이 어떤지 제안드립니다.

2023-09-16 12:17 UTC, greeng00se commented
refresh 토큰이 도입되었음으로 close 하겠습니다

2023-09-16 12:17 UTC, closed without merging