[refactor] 여행 히스토리 / 이미지 관련 수정 및 버그 잡기 (#302)
woowacourse-teams/2023-trip-draw pull request #347
Opened 2023-09-10 08:51 UTC by pingu244

### 📌 관련 이슈

- closed #302 

### 📁 작업 설명

- 기본 이미지를 추가한다
- 이미지 빈 값인 경우 빈 String으로 처리
- 지도 위치 이동 버그 잡기

### 📸 작업화면
<img width="311" alt="image" src="https://github.com/woowacourse-teams/2023-trip-draw/assets/69796976/c6ff9018-3e49-4ff8-8a7a-0ad6277f536e">
<img width="314" alt="image" src="https://github.com/woowacourse-teams/2023-trip-draw/assets/69796976/39383992-6636-4974-bf89-7e36e1304628">

2023-09-13 12:33 UTC, 2chang5 requested changes
전체적으로 null 관련 변화가 많이 일어났는데 혹시 서버와 합의사항에서 변경이 일어났나요? 궁금합니다!!

2023-09-13 12:33 UTC, 2chang5 commented on android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/response/GetPostResponse.kt
> +    val routeImageUrl: String,
nullable 에서 변경된 사유가 궁금합니다. 서버와 협의 사안이 변경되었나요?

2023-09-13 12:33 UTC, 2chang5 commented on android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/response/GetTripInfoResponse.kt
> +    val routeImageUrl: String,
이 부분도 마찬가지로 궁금합니다!!

2023-09-13 12:33 UTC, 2chang5 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/CommonBindingAdapter.kt
> +        .placeholder(R.drawable.shape_td_logo_fill_10_rect)
R.drawable.shape_td_logo_fill_10_rect 가 이미 radius 를 이미 준것같은데 transform 과 중복된것 아닌가요?
또한 R.drawable.shape_td_logo_fill_10_rect은 저희 컨벤션과 맞지 않은것 같습니다!!!

2023-09-13 12:33 UTC, 2chang5 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/ImageBindingAdapter.kt
> +    if (imgUrl == null || imgUrl.isBlank()) {
isNullOrBlank를 사용해보면 어떨까요? 기존에 있는 기능을 이용해도 좋을것 같아요!!

2023-09-13 12:33 UTC, 2chang5 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/ImageBindingAdapter.kt
>  fun ImageView.setImageWithVisibility(imgUrl: String?) {
bindingAdapter또한 전역에서 사용가능한 함수입니다.
with 이라는 단어가 함수명에 들어있는게 SRP를 위반한다는 신호라는 생각이 듭니다!!!
visibility와 이미지를 변경하는 함수를 나누고 두가지 모두 바인딩을 거는것은 어떤가 제시해봅니다!!

2023-09-13 12:33 UTC, 2chang5 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/ImageBindingAdapter.kt
>  @BindingAdapter("app:setRoundImageWithVisibility")
srp에 대한것은 위의 리뷰와 같습니다!!!

2023-09-13 12:33 UTC, 2chang5 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/ImageBindingAdapter.kt
> +    if (imgUrl.isBlank()) {
이 바인딩 어댑터만 위와 다르게 nullable 하지않은 값이 들어오나요? 둘다 비슷한 환경에서 호출될것 같은데 두개가 차이가 보여서 무슨차이인지 알려주시면 감사드리겠습니다!!

2023-09-13 12:33 UTC, 2chang5 commented on android/app/src/main/java/com/teamtripdraw/android/ui/history/detail/HistoryDetailActivity.kt
> -
ㅋㅋㅋㅋ 앓던이가 빠졌군요 앓던이가 실수였다니

2023-09-13 12:33 UTC, 2chang5 commented on android/app/src/main/res/drawable/shape_td_logo_fill_10_rect.xml
이부분은 저희 컨벤션에 맞지않는것 같아요!!! 만약 라운드 이미지가 필요하다면 피그마에서 라운드로 깎고 이미지를 재다운로드 받아서 컨벤션에 맞추는게 좋을것 같아보입니다!!

2023-09-14 00:08 UTC, otter66 approved these changes
제가 할 말이 전부 나왔군요ㅎㅎ 
수고하셨습니다! 열심히 사는 핑구 화이팅!

2023-09-14 06:08 UTC, pingu244 commented on android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/response/GetPostResponse.kt
> +    val routeImageUrl: String,
서버측에서 이미지가 없다면 null을 보낼지 빈 String 값을 보낼지 물어봤었습니다.
nullable보다는 빈 String이 안정적일 것 같아 이렇게 변경했습니다!

2023-09-14 11:59 UTC, pingu244 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/ImageBindingAdapter.kt
> +    if (imgUrl.isBlank()) {
위에서 말씀드렸던 것처럼 이제 이미지 url는 null값을 가지지 않습니다.
하지만 liveData로 지정한 값은 초기에 null로 초기화되었다가 값이 들어오게 됩니다. 이것을 nullable로 해두지 않으면 nullable하지 않은 자리에 null이 들어왔다며 오류가 나서 터지게 됩니다.

그런데 지금 이 함수처럼 null이 들어오지 않는 상황이 있습니다.
RecyclerView의 Item과 같은 곳에는 liveData로 사용하지 않고 model을 그대로 사용하기 때문에 null이 될 일이 없습니다.

어쩌다보니 setRoundImageWithVisibility는 item에서밖에 사용하지 않게 되어 이렇게 되었네요ㅋㅋ
앞으로 다른 곳에서 사용할 가능성이 있으니 이 함수도 nullable한 값을 받도록 수정하겠습니다!

2023-09-14 13:03 UTC, pingu244 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/ImageBindingAdapter.kt
>  fun ImageView.setImageWithVisibility(imgUrl: String?) {
아주 좋은 생각인 것 같습니다!! setImageVisibility()를 따로 만들어주었습니다

2023-09-14 13:14 UTC, pingu244 commented on android/app/src/main/res/drawable/shape_td_logo_fill_10_rect.xml
이 파일 자체가 좀 억지인 것 같아서 필요한 부분의 이미지들을 넣어서 사용하게 수정했습니다

2023-09-14 13:20 UTC, pingu244 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/CommonBindingAdapter.kt
> +        .placeholder(R.drawable.shape_td_logo_fill_10_rect)
placeholder 나 error에 넣어주는 리소스는 transform이 적용되지 않더라구요

2023-09-16 10:59 UTC, 2chang5 submitted a review, later dismissed
분리가 필요하거나 네이밍의 수정이 이루어져야 할것 같습니다. 전체적으로 리뷰를 한번 쭉 훑어 보시고 결정하면 좋을것 같습니다.

2023-09-16 10:59 UTC, 2chang5 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/CommonBindingAdapter.kt
> +fun ImageView.setImage(imgUrl: String?) {
nullable 하게 변경하신 이유가 궁금합니다 서버와 빈스트링값으로 통일한것 아닌가요?

2023-09-16 10:59 UTC, 2chang5 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/CommonBindingAdapter.kt
> +        .error(R.drawable.img_default_image)
디폴트 이미지를 error로 작성하신것 같은데 적절하지 못하다고 생각합니다.
fallback 기능을 이용해보는건 어떨까요?

2023-09-16 10:59 UTC, 2chang5 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/CommonBindingAdapter.kt
> +        .error(R.drawable.img_default_image)
이 부분은 일반적인 이미지를 다루는 바인딩어댑터에 이미지를 로드하지 못하는 상황입니다.이때 일괄적으로 로고 이미지 이미지를 넣는것이 상황상 맞나 고민해보면 좋을것 같습니다. 이건 핑구가 개발하는 부분의 특정상황이라고 생각하여 common의 상황이 아니라고 생각됩니다.

2023-09-16 10:59 UTC, 2chang5 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/ImageBindingAdapter.kt
> +    if (imgUrl.isNullOrBlank()) {
이 바인딩 어댑터 또한 common 의 성격을 지니는데 과연 이미지 로딩이 안될시 visibility자체를 gone으로 없애는게 일반적인 상황인지 고민해보면 좋을것 같습니다. gone을 사용할 때 그에 대한 대처가 안되있는 상황이면 화면 구성 자체가 일그러질 수 있습니다.

2023-09-16 10:59 UTC, 2chang5 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/ImageBindingAdapter.kt
> +        .error(R.drawable.img_default_image)
위와 같은 코멘트 입니다. 이 바인딩 어댑터는 네이밍상 일반적인 상황을 다룬다고 생각합니다. 
현재까지 다루는 바인딩 어댑터들이 특정한 상황에 대처하는것 같아서 바인딩 어댑터를 애초에 분리해내고 상황에 맞게 네이밍해줘야 한다고 생각합니다.

2023-09-16 10:59 UTC, 2chang5 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/ImageBindingAdapter.kt
> +fun ImageView.setFileVisibility(imgFile: File?) {
이런 부분에 있어서 만약 일반적인 사용을 할수 있도록 하고싶으시다면 네이밍을 정말 자세히 적어주셔서 네이밍만 보고도 어떤 행위를 하는지 파악할 수 있도록하여 재활용을 유도해야한다고 생각합니다.

2023-09-16 18:08 UTC, pingu244 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/CommonBindingAdapter.kt
> +fun ImageView.setImage(imgUrl: String?) {
https://github.com/woowacourse-teams/2023-trip-draw/pull/347#discussion_r1325841896 이 답변을 참고해주세요!
liveData로 받아오는 과정에서 불가피한 상황이라고 생각합니다

2023-09-17 08:54 UTC, pingu244 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/CommonBindingAdapter.kt
> +        .error(R.drawable.img_default_image)
제 개인적인 생각으로는 에러 상황에서도 로고 이미지를 넣는 것이 맞다고 생각합니다.
물론 밑에 에러 상황이라고 스낵바, 토스트를 띄워주긴 해야겠지만 이미지가 로드되지 않는다고 회색 이미지를 보여주는 것보다는 기본 이미지인 로고가 보이는 것이 낫다고 생각해요!

2023-09-17 08:57 UTC, pingu244 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/ImageBindingAdapter.kt
> +    if (imgUrl.isNullOrBlank()) {
저희 디자인 상에서 이미지가 없다면 Gone을 해야하기 때문에 해당 바인딩어댑터를 만들게 되었습니다.
해당 기능이 필요한 곳에서만 사용하니 괜찮지 않을까요?

2023-09-17 08:58 UTC, pingu244 commented on android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/ImageBindingAdapter.kt
> +fun ImageView.setFileVisibility(imgFile: File?) {
역시 이름짓기가 제일 힘들군요.....

2023-09-17 14:05 UTC, merged