[refactor] OAuth API 호출에 해당하는 부분을 트랜잭션에서 제외 (#349)
woowacourse-teams/2023-trip-draw pull request #350
Opened 2023-09-13 06:11 UTC by greeng00se

### 📌 관련 이슈

- closed #349 

### 📁 작업 설명

- OAuth API 호출에 해당하는 부분을 트랜잭션에서 제외했습니다.
- register의 경우 TransactionTemplate 내부에서 generateToken을 호출하고, generateToken의 경우에 내부에 TransactionTemplate이 적용되어 있는 부분이 있습니다. 이 경우 REQUIRES로 동작하기 때문에 트랜잭션에 참여하는 형태로 동작할 것 같습니다.

2023-09-14 08:17 UTC, Jaeyoung22 requested changes
고생했습니다! 커멘트 확인하고 의견 남겨주세요!

2023-09-14 08:17 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/auth/application/AuthService.java
> +            Member member = memberRepository.findByOauthIdAndOauthType(oauthInfo.oauthId(), oauthInfo.oauthType())
MemberRepository의 역할로 두어서 다른 Repository와 통일성을 갖추는 건 어떨까요?

2023-09-14 08:20 UTC, Combi153 requested changes
TransactionTemplate 이 Transaction 안에서 동작하도록 만든 Template인가요?
설명이나 참고자료를 주시면 감사하겠습니다.

고생하셨어요!

2023-09-14 08:20 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/auth/application/AuthService.java
>      }
login은 Transaction 설정을 하지 않아도 되는 이유가 무엇인가요?
제가 Transaction 공부 좀 하겠습니다

2023-09-14 08:56 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/auth/application/AuthService.java
>      }
generateToken 내부에 TransactionTemplate이 적용되어있습니다

2023-09-14 15:22 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/auth/application/AuthService.java
>      }
추가로 TransactionTemplate 관련 내용은 정리해서 주말에 올려드릴게요!
현재는 리오가 말한대로 가독성이 좋지 못한 부분이 있는 것 같아서 서비스를 분리해보는 방향으로 진행하도록 하겠습니다!

2023-09-14 16:05 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/auth/application/AuthService.java
>      }
Transaction 공부 했고, 로직 이해했습니다!
Transaction 적절히 분리한 게 맞네요! 좋습니다 👍 

TransactionTemplate 도 이해했습니다. Spring에서 제공하는 프로그래밍적 트랜잭션 관리 방법이군요

서비스를 분리하는 것은 적절한 선택지 같습니다. 지금 가독성이 떨어지는 문제를 다시 `@Transactional`를 사용함으로써 극복할 수 있지 않을까? 생각됩니다.

2023-09-16 11:31 UTC, Combi153 approved these changes
깔끔한 코드네요

고생하셨습니다!

2023-09-16 11:31 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/auth/application/AuthFacadeService.java
> +                .orElseGet(tokenGenerateService::generateEmptyToken));
authService, tokenGenerateService의 `@Transactional`이 REQUIRED 설정이 되어있어서, 여기서 시작한 트랜잭션이 그대로 이어지는 거군요 👍

2023-09-16 11:31 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/test/fixture/MemberFixture.java
> +}
이미 만들어 둔 거 안쓰고 새로 만든 이유가 있나요?

2023-09-16 11:35 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/auth/application/AuthFacadeService.java
> +public class AuthFacadeService {
이름에 Facade를 넣는 것이 살짝 묘하네요.

다음과 같이 바꾸는 건 어떨지 제안해봅니다~

AuthService(전) -> BasicAuthService(후), AuthFacadeService(전) -> AuthService(후)

2023-09-16 11:41 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/test/fixture/MemberFixture.java
> +}
각각의 Fixture로 하나씩 분리해가려고 합니다!

2023-09-16 11:43 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/auth/application/AuthFacadeService.java
> +public class AuthFacadeService {
Facade라고 명시해둬야 된다고 생각합니다. 
BasicAuthService는 Basic 인증을 처리하는 느낌이 듭니다. 기존의 서비스와 구분을 하기 위해 AuthServiceFacade + AuthService는 어떨까요?

2023-09-18 05:52 UTC, Jaeyoung22 approved these changes
고생했습니다
요청에 의해 우선 빠르게 어프루브하고 논의 사항 후에 discussion에 남기겠습니다

2023-09-18 05:54 UTC, Combi153 approved these changes
고생하셨습니다~ 👍

2023-09-18 05:54 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/member/presentation/MemberController.java
> +        MemberSearchResponse response = memberService.find(loginUser);
이 방식이 훨씬 좋은 것 같습니다 👍

2023-09-18 05:54 UTC, merged