[feat] ControllerAdvice 적용하여 예외 처리 (#30)
woowacourse-teams/2023-trip-draw pull request #36
Opened 2023-07-18 15:04 UTC by Jaeyoung22

## 관련 이슈번호
- closed #30

## 작업 설명
- ControllerAdvice 적용

2023-07-18 17:46 UTC, Combi153 approved these changes
고생하셨습니다 리오~ 👍 👍

2023-07-18 17:46 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/presentation/controller/ControllerExceptionHandler.java
> +    }
이것도 메서드니까 동사로 시작하면 어떨까요?
`handlerAuthException` -> `handleAuthException`

2023-07-18 17:50 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/presentation/controller/ControllerExceptionHandler.java
> +
logger 추가, 기타 간단한 예외 처리는 이번에 해도 좋을 것 같다는 생각이 드네요!

2023-07-18 17:51 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/presentation/controller/ControllerExceptionHandler.java
> +    }
logger 추가, 기타 간단한 예외 처리는 이번에 해도 좋을 것 같은데 어떠신가요?

2023-07-18 21:41 UTC, greeng00se requested changes
고생하셨습니다. 👍 
후추 말대로 logger 정도는 추가한 다음 merge 하면 좋을 것 같아요!
그리고 예외의 경우에는 오늘 안드로이드랑 같이 조금 더 이야기 하는 시간을 가져야할 것 같아요.

2023-07-18 21:41 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/presentation/controller/ControllerExceptionHandler.java
> +public class ControllerExceptionHandler {
InternalServerError를 던지는 기본 예외 처리(Exception)의 추가를 추가해보는건 어떨까요?

2023-07-19 01:39 UTC, greeng00se approved these changes
머지 후 해당 부분 페어프로그래밍 진행하기로 했습니다.

2023-07-19 01:46 UTC, beer-2000 commented on backend/src/main/java/dev/tripdraw/dto/response/ExceptionResponse.java
> +public record ExceptionResponse(ExceptionCode exceptionCode) {
다른 클래스(ExceptionCode)에 관한 얘기이긴한데,
네이밍이 ExceptionCode라서 -> 코드(번호)가 있을 거라는 기대가 생기는 것 같아요.
ExceptionType 과 같은 네이밍이 어떤지 제안드려봅니다.
지금도 괜찮습니다!

2023-07-19 01:46 UTC, beer-2000 approved these changes
허브가 남겨주신 '기본 예외 처리' 외에는 괜찮은 것 같고,
ExceptionCode 네이밍 관련 코멘트도 하나 남겼지만, 단순 제안이라
approve 하겠습니다~~

2023-07-19 01:47 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/presentation/controller/ControllerExceptionHandler.java
> +    }
좋습니다! 반영하겠습니다!

2023-07-19 01:47 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/presentation/controller/ControllerExceptionHandler.java
> +public class ControllerExceptionHandler {
좋습니다~!

2023-07-19 01:47 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/dto/response/ExceptionResponse.java
> +public record ExceptionResponse(ExceptionCode exceptionCode) {
좋습니다~!

2023-07-19 01:47 UTC, merged