[feat] 여행 전체 조회 기능 추가 (#361) (아직 작업 중)
woowacourse-teams/2023-trip-draw pull request #364
Opened 2023-09-16 18:08 UTC by Combi153

### 📌 관련 이슈

- closed #361

### 📁 작업 설명

- 아직 작업 중

2023-09-18 12:44 UTC, greeng00se requested changes
안녕하세요 후추 고생하셨습니다! 일정이 빡빡한데 빨리 구현한다고 고생하셨습니다! 👍 👍 
코멘트 몇개 남겼으니 확인해주시면 감사하겠습니다!
추가로 Condition을 적용한 Controller 테스트가 하나 정도 있으면 좋을 것 같습니다!

2023-09-18 12:44 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/common/config/QueryDslConfig.java
> +    }
빈 생성자를 제거하는건 어떤가요?!

2023-09-18 12:44 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/trip/application/TripQueryService.java
> +        );
한 줄로 작성하는건 어떨까요?

2023-09-18 12:44 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/trip/application/TripQueryService.java
> +@Transactional
QueryService의 경우 클래스단에 readOnly를 적용하는건 어떤가요?

2023-09-18 12:44 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/trip/query/TripCustomRepositoryImpl.java
> +        if (CollectionUtils.isEmpty(years)) {
null check를 위해 CollectionUtils를 사용하셨군요 👍

2023-09-18 12:44 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/trip/domain/TripQueryConditionsTest.java
> +    }
경계값 테스트 👍

2023-09-18 12:44 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/trip/application/TripService.java
>      private final TripRepository tripRepository;
한 칸 띄우면 좋을 것 같아요 👍

2023-09-18 12:44 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/trip/application/TripService.java
> +    private final TripQueryService tripQueryService;
TripService가 TripQueryService를 사용하고 있는데 혹시 어떤 이유로 QueryService를 사용하는지 코멘트 남겨주실 수 있나요?

2023-09-18 12:44 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/trip/dto/TripSearchResponse.java
> +        LocalDateTime endTime
일관성을 위해서 Schema를 추가하는 것도 좋을 것 같습니다.

2023-09-18 12:44 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/trip/dto/TripSearchConditions.java
> +) {
```
@Builder
public record TripSearchConditions(
        Set<@Range(min = 2010, max = 2023) Integer> years,
        Set<@Range(min = 1, max = 12) Integer> months,
        Set<@Range(min = 1, max = 7) Integer> daysOfWeek,
        Set<@Range(min = 1, max = 10) Integer> ageRanges,
        Set<@Range(min = 1, max = 2) Integer> genders,
        String address
) {

    public TripQueryConditions toTripQueryConditions() {
        return new TripQueryConditions(years(), months(), daysOfWeek(), ageRanges(), genders(), address());
    }
}

Validation을 이용하는건 어떨까요?
```

2023-09-18 12:44 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/trip/query/TripCustomRepositoryImpl.java
> +public class TripCustomRepositoryImpl implements TripCustomRepository {
TripQueryRepository로 변경하고 implements를 제거하는건 어떤가요?

2023-09-19 04:02 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/common/config/QueryDslConfig.java
> +    }
우렁각시가 만들어줬어요 제가 안 만들었어요

2023-09-19 04:38 UTC, greeng00se approved these changes
고생하셨습니다 👍

2023-09-19 04:44 UTC, Jaeyoung22 requested changes
어프루브 요청하셨지만 RC합니다 확인해주세요

2023-09-19 04:44 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/trip/dto/TripSearchConditions.java
> +        return new TripQueryConditions(years(), months(), daysOfWeek(), ageRanges(), genders(), address());
TripQueryConditions에도 빌더패턴 적용하면 좋을 것 같아요~

2023-09-19 04:44 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/test/fixture/TripSearchConditionsFixture.java
> +        return new TripSearchConditions(
TripSearchConditions에도 빌더 패턴 적용하면 필요한 프로퍼티만 설정할 수 있어서 테스트 코드가 깔끔해질 것 같아요!

2023-09-19 06:04 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/test/fixture/TripSearchConditionsFixture.java
> +        return new TripSearchConditions(
적용 완료 했습니다~

2023-09-19 06:04 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/trip/dto/TripSearchConditions.java
> +        return new TripQueryConditions(years(), months(), daysOfWeek(), ageRanges(), genders(), address());
TripQueryConditions 지우고 TripSearchConditions 만 사용하도록 리팩터링 했습니다!

2023-09-19 06:06 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/trip/dto/TripSearchConditions.java
> +) {
리오는 아직 적용을 안 했던데, 일단은 두고 추후 함께 적용하겠습니다

2023-09-19 06:23 UTC, Jaeyoung22 approved these changes
고생하셨습니다!

2023-09-19 06:23 UTC, merged