Feature/#363
woowacourse-teams/2023-trip-draw pull request #367
Opened 2023-09-17 18:49 UTC by Jaeyoung22

### 📌 관련 이슈

- closed #363 

### 📁 작업 설명

- 조건별로 감상을 전체 조회하는 기능을 구현했습니다.

### 💻 미완료 태스크(선택)

- [ ] 인덱스를 위한 DB Schema 변경
- [ ] 가입 시 연령대와 성별 받아오기
- [ ] 해가 지나면 나이 업데이트 어떻게 할지

2023-09-17 23:57 UTC, greeng00se requested changes
새로운 기술을 빨리 학습하고 기능 추가를 해주신 부분 정말 대단한 것 같습니다.
기능 구현에 있어서는 군더더기 없이 깔끔하게 구현해주신 것 같아서 기능 이외에 부분에 코멘트를 남겼습니다.
후추와 같이(둘 다 querydsl 사용하니) 이야기를 나누고 고민해보셨으면 합니다.

2023-09-17 23:57 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/common/domain/Paging.java
> +}
해당 클래스가 domain 패키지에 위치하는건 조금 고민해볼 수 있을 것 같아요.
계층을 나누기 위해 Paging과 SearchPaging을 분리하신 것 같습니다!
VO 하나로 통일해보는건 어떠신가요?

2023-09-17 23:57 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/post/application/PostService.java
> +        Paging paging = postSearchRequest.paging().toPaging();
만약 지금과 같이 SearchConditions의 계층 분리를 하신다면 getter를 사용한 후 메서드를 호출하는 것 보다 postSearchRequest에서 바로 postSearchRequest.toSearchConditions()이 더 가독성이 좋아보이는데 어떻게 생각하시나요?
아래의 paging도 동일한 의견입니다.

2023-09-17 23:57 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/post/domain/PostCustomRepository.java
> +}
QueryDsl 관련 클래스(repositioy, repositoryImpl)들이 domain 패키지에 있는 부분에 대해 어떻게 생각하시나요? query용 패키지 및 queryService를 따로 분리하는 것도 좋을 것 같습니다.

2023-09-17 23:57 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/post/domain/PostCustomRepositoryImpl.java
> +        QPost post = QPost.post;
QPost를 변수 추출하지 않고 static import 해보는건 어떠신가요?

2023-09-17 23:57 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/post/domain/PostCustomRepositoryImpl.java
> +        return post.id.lt(lastViewedId);
QueryDsl 마스터? 👍

2023-09-17 23:57 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/post/dto/PostsSearchResponse.java
> +    }
클라이언트와 hasNextPage에 대한 정보만 제공하기로 합의하셨군요 👍

2023-09-17 23:57 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/post/application/PostServiceTest.java
> +        PostsSearchResponse postsSearchJulyResponse = postService.readAll(postSearchRequestJuly);
하나의 메서드에서 여러 개 검증을 하는 것보다 메서드를 분리해서 2개의 테스트 메서드를 작성하는 건 어떨까요?
Repository도 같은 의견입니다!

2023-09-17 23:57 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/post/presentation/PostControllerTest.java
> +        assertThat(postsSearchResponse.posts().get(1).postId()).isEqualTo(jejuAugust17hourPostResponse.postId());
controller나 service 검증부에 id만 검증하게 되는 경우 개인적인 경험으로 휴먼에러로 인해 실제로 데이터가 제공되지 않는 경우가 종종 있었어요. 모든 필드에 대해 검증해보는건 어떨까요?

2023-09-18 00:01 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/post/domain/PostCustomRepositoryImpl.java
> +    private BooleanExpression eqAdress(StringPath address, String targetAddress) {
메서드명에 d 하나 빠졌네용~

2023-09-19 04:22 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/common/domain/Paging.java
> +}
VO 하나로 통일하고, 패키지 분리했습니다!

2023-09-19 04:23 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/post/application/PostService.java
> +        Paging paging = postSearchRequest.paging().toPaging();
VO를 하나로 통일하면서 해결됐습니다!

2023-09-19 04:23 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/post/domain/PostCustomRepository.java
> +}
좋네요 분리했습니다!

2023-09-19 04:24 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/post/domain/PostCustomRepositoryImpl.java
> +        QPost post = QPost.post;
훨씬 깔끔해졌네요!

2023-09-19 04:26 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/post/application/PostServiceTest.java
> +        PostsSearchResponse postsSearchJulyResponse = postService.readAll(postSearchRequestJuly);
같은 GIVEN 조건이라면 하나의 메서드 안에 있는 것을 선호하는 편입니다! 허브는 어떻게 생각하실까요?

2023-09-19 04:27 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/post/presentation/PostControllerTest.java
> +        assertThat(postsSearchResponse.posts().get(1).postId()).isEqualTo(jejuAugust17hourPostResponse.postId());
일단 ID로 비교하고 추후에 조금 더 추가하겠습니다!

2023-09-19 04:27 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/post/domain/PostCustomRepositoryImpl.java
> +    private BooleanExpression eqAdress(StringPath address, String targetAddress) {
매의 눈

2023-09-19 04:31 UTC, greeng00se approved these changes
고생하셨습니다 👍

2023-09-19 04:32 UTC, merged