[refactor] Member 간접참조로 변경 #403
woowacourse-teams/2023-trip-draw pull request #406
Opened 2023-09-25 12:45 UTC by Combi153

### 📌 관련 이슈

- closed #403 

### 📁 작업 설명

- 현재 Trip, Post 가 Member를 직접 참조하고 있습니다. 하지만 직접 참조의 이점을 누리는 기능이 없습니다. 불필요한 참조를 줄이기 위해 간접 참조로 변경했습니다.
- 인가 처리 시 member를 조회하는 쿼리를 하나 줄였습니다.
- 인가 처리 시 memberId로 하도록 변경했습니다.

### 이슈

리팩터링을 하면서 두 가지 문제를 발견했습니다.

각각 이슈를 생성해두었습니다.

- opened #404
- opened #405

### 고민

`회원의 닉네임이 없을 경우 어떻게 처리를 할지` 고민이 됩니다.

```java
public interface MemberRepository extends JpaRepository<Member, Long> {

    @Query("SELECT m.nickname FROM Member m WHERE m.id = :id")
    Optional<String> findNicknameById(@Param("id") Long id);

    default String getNicknameById(Long id) {
        return findNicknameById(id)
                .orElseThrow(() -> new MemberException(MEMBER_NOT_REGISTERED));
    }
}
```

닉네임이 없는(null) 경우는 두 가지입니다.
1. register 를 하지 않은 회원
2. register 시 nickname을 null로 둔 회원

두 가지 경우 모두, 다른 코드에서 검증을 진행할 경우 Repository에서 이를 검증을 꼭 할 필요가 있을지 고민됩니다.

현재는 1, 2 모두 검증이 안 되어 있기에 일단 검증 로직은 작성해두었습니다.

2023-09-25 14:59 UTC, Jaeyoung22 requested changes
고생했습니다 커멘트 확인해주세요

2023-09-25 14:59 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/member/domain/MemberRepository.java
> +                .orElseThrow(() -> new MemberException(MEMBER_NOT_REGISTERED));
예외 명이 이해가 되는데 처음 보는 사람은 MEMBER_NOT_FOUND와 뭐가 다른지 헷갈릴 거 같아요
그리고 MEMBER_NOT_REGISTERED 의 예외 사항에 MEMBER_NOT_FOUND의 예외 사항이 포함 되어 있네요
두 예외를 통일하는 건 어떻게 생각하시나요?

2023-09-25 14:59 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/member/exception/MemberExceptionType.java
> +    MEMBER_NOT_REGISTERED(INTERNAL_SERVER_ERROR, "가입이 완료되지 않은 회원이 존재합니다."),
위에서 얘기했지만, 여기서 예외 메세지를 `가입이 완료되지 않은 회원이 존재합니다`라고 한다면 getNicknameById() 에서 id 자체가 존재하지 않는 경우를 확인할 수 없을 것 같아요

2023-09-25 14:59 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/post/application/PostService.java
> +        Long memberId = loginUser.memberId();
👍

2023-09-25 16:47 UTC, greeng00se requested changes
만약 이렇게 변경된 후에, admin 기능이 추가된다면 어떻게 해야할까요? 후추의 의견이 궁금합니다!

2023-09-26 08:26 UTC, Combi153 commented
@greeng00se 
admin 기능을 만들어 본 적이 없어서 구체적으로는 어떤 기능이 필요할지 모르겠습니다. 

지금 짧게 생각하기로는 Member의 권한을 확인하는 기능이 필요할 것 같아요.

그에 대해서는 Member entity 에 권한에 관한 컬럼을 추가하고, 이를 Repository에서 확인하면 어떨까 싶습니다.

2023-09-26 08:39 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/member/domain/MemberRepository.java
> +                .orElseThrow(() -> new MemberException(MEMBER_NOT_REGISTERED));
동의합니다. 여기서 회원의 닉네임에 관한 예외를 굳이 잡을 필요는 없을 것 같아요! 그리고 이 메서드를 실행할 시점에는 이미 interceptor 를 지나왔기 때문에 MEMBER_NOT_FOUND 예외도 잡을 필요가 없을 것 같습니다.

아예 예외를 잡지 않는 것에 대해서는 어떻게 생각하시나요?

2023-09-26 08:41 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/member/exception/MemberExceptionType.java
> +    MEMBER_NOT_REGISTERED(INTERNAL_SERVER_ERROR, "가입이 완료되지 않은 회원이 존재합니다."),
넵 해당 예외는 지우도록 하겠습니다!

2023-09-26 13:50 UTC, greeng00se approved these changes
고생하셨습니다 👍 
저도 어드민 관련해서는 조금 더 고민을 해봐야할 것 같습니다 ㅎㅎ

2023-09-26 13:53 UTC, Jaeyoung22 approved these changes
고생했습니다!

2023-09-27 04:57 UTC, merged