[refactor] Point와 Trip Controller, Service 분리
woowacourse-teams/2023-trip-draw pull request #441
Opened 2023-10-04 07:04 UTC by greeng00se

### 📌 관련 이슈

- closed #440 

### 📁 작업 설명

- Point Controller와 Service를 TripController, TripService에서 분리하였습니다!

2023-10-04 07:19 UTC, Combi153 approved these changes
고생하셨습니다~
꼼꼼히 @RequestMapping 바꿔주셨네요!

2023-10-08 09:40 UTC, Jaeyoung22 requested changes
고생하셨습니다. 커멘트 확인해주세요.

2023-10-08 09:40 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/trip/application/PointService.java
> +        trip.validateAuthorization(loginUser.memberId());
이거 혹시 언제 사용하나요?
다른 사람의 여행 경로 조회할 때 사용이 될 수 있을 것 같은데 validation이 있으면 예외 발생할 것 같아요.
다른 사람의 여행 경로 조회할 때 위치정보 조회도 같이 일어나는지 확인해봐야할 것 같아요

2023-10-08 09:44 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/trip/application/PointService.java
> +        trip.validateAuthorization(loginUser.memberId());
이건 이슈파서 새로 고쳐야 할 것 같아요.

2023-10-08 09:45 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/trip/application/PointService.java
> +        trip.validateAuthorization(loginUser.memberId());
해당 PR이랑 같이 수정해서 올리는게 좋을까용?

2023-10-08 09:48 UTC, Jaeyoung22 approved these changes
발견한 버그는 다른 PR 파서 해결하는 걸로 합의했습니다

2023-10-08 09:48 UTC, merged