[feat] 어드민 페이지를 위한 API를 개발한다 #454
woowacourse-teams/2023-trip-draw pull request #459
Opened 2023-10-10 07:49 UTC by greeng00se

### 📌 관련 이슈

- closed #454 

### 📁 작업 설명

다음과 같은 기능을 구현하였습니다.

어드민 로그인 기능 POST /admin/login
여행 전체 조회 기능 GET /admin/trips
감상 전체 조회 기능 GET /admin/posts
여행 단일 조회 기능 GET /admin/trips/{tripId}
감상 단일 조회 기능 GET /admin/posts/{postId}
여행 삭제 기능 DELETE /admin/trips/{tripId}
감상 삭제 기능 DELETE /admin/posts/{postId}

2023-10-11 01:47 UTC, Jaeyoung22 requested changes
고생했습니다 커멘트 확인해주세요

2023-10-11 01:47 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/admin/domain/Admin.java
> +        if (failCount >= MIN_FAIL_COUNT) {
의미상 MAX_FAIL_COUNT 여야할 것 같아요~

2023-10-11 01:47 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/admin/application/AdminService.java
> +    public void deleteTrip(Long tripId) {
나는 아무리 봐도 띠용하네... 트랜잭션 명시 안되어있는 느낌이랄까...

2023-10-11 01:47 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/admin/application/PasswordEncoder.java
> +import org.mindrot.jbcrypt.BCrypt;
BCrypt를 선택한 이유를 문서화해주시면 좋을 것 같아요~

2023-10-11 01:47 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/admin/application/AdminService.java
> +    public void deleteTrip(Long tripId) {
+ `deleteTripById(Long tripId)` 가 아닌 이유가 있나요?
아니면 위의 readTripById가 readTrip이어야 할 거 같아요

2023-10-11 01:47 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/admin/application/AdminService.java
> +        postRepository.deleteById(postId);
ditto

2023-10-11 01:47 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/admin/config/AdminConfig.java
> +                .excludePathPatterns("/admin/login");
애매하긴 한데 최선의 의식의 흐름이군요..

2023-10-11 01:47 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/admin/domain/Admin.java
> +    private Long failCount;
MIN_FAIL_COUNT는 int이고, failCount는 Long인 이유가 있나요?

2023-10-11 01:47 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/admin/presentation/AdminController.java
> +    public ResponseEntity<AdminTripResponse> readTrips(@PathVariable("tripId") Long tripId) {
메서드명이 readTrips인 이유가있나요?

2023-10-11 01:47 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/admin/presentation/AdminController.java
> +    public ResponseEntity<AdminPostResponse> readPosts(@PathVariable("postId") Long postId) {
ditto

2023-10-11 01:47 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/post/query/PostCustomRepositoryImpl.java
> +import lombok.RequiredArgsConstructor;
ㅋㅋ... 가끔 들러서 고쳐주고 가세요~~ ㅎㅎ.. 고맙습니다..

2023-10-11 01:47 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/trip/domain/TripName.java
> +    public TripName(String name) {
??????

2023-10-11 01:47 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/admin/application/AdminAuthServiceTest.java
> +    void 비밀번호를_5회_이상_틀리는_경우_예외가_발생한다() {
정책이 바뀔 수 있으니 최대 틀릴 수 있는 횟수(?) 등으로 테스트 이름을 바꾸는 건 어떨까요?

2023-10-11 01:47 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/admin/domain/AdminTest.java
> +    void 인증_실패_카운트가_5회를_초과하는_경우_예외를_던진다() {
ditto

2023-10-11 02:01 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/admin/domain/Admin.java
> +        if (failCount >= MIN_FAIL_COUNT) {
굳굳 👍

2023-10-11 02:01 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/admin/application/AdminService.java
> +    public void deleteTrip(Long tripId) {
띠용? 둘 중 하나로 통일할게용~

2023-10-11 02:04 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/admin/application/PasswordEncoder.java
> +import org.mindrot.jbcrypt.BCrypt;
추후에 문서로 작성하고 해당 PR에서는 링크로 대체할게요!
평문 저장, SHA256, BCrypt 고려했고 그 중 가장 안전한 Bcrypt 사용했어요
https://d2.naver.com/helloworld/318732

2023-10-11 02:05 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/admin/domain/Admin.java
> +    private Long failCount;
ㅋㅋ 정신없이 코딩했네요 Long으로 통일하겠습니당

2023-10-11 02:06 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/admin/presentation/AdminController.java
> +    public ResponseEntity<AdminTripResponse> readTrips(@PathVariable("tripId") Long tripId) {
오 매의 눈 ㄷㄷ

2023-10-11 02:07 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/post/query/PostCustomRepositoryImpl.java
> +import lombok.RequiredArgsConstructor;
???? 자동으로 고쳐진건ㄷ...

2023-10-11 02:08 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/trip/domain/TripName.java
> +    public TripName(String name) {
생성자 닫혀있으니 테스트 작성할 때 유연성이 너무 떨어지더라고용

2023-10-11 02:11 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/admin/application/AdminAuthServiceTest.java
> +    void 비밀번호를_5회_이상_틀리는_경우_예외가_발생한다() {
적절한 네이밍 없을까요? 최대 틀릴 수 있는 횟수로 사용하면 테스트 가독성이 안좋아지네요 ㅠㅠ

2023-10-11 02:29 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/admin/application/AdminAuthServiceTest.java
> +    void 비밀번호를_5회_이상_틀리는_경우_예외가_발생한다() {
최대 실패 가능 횟수 어떻습니까

2023-10-11 02:30 UTC, Jaeyoung22 approved these changes
고생하셨씁니다!

2023-10-11 06:00 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/admin/application/AdminAuthService.java
> +        }
failCount 맛.있.다.!

2023-10-11 06:02 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/admin/application/PasswordEncoder.java
> +    }
간단하게 솔팅할 수 있어 좋군요.

그런데 이 메서드가 사용되는 곳이 테스트 코드말고 없네요. Admin 에 대한 회원가입(?) 과정은 어떻게 하실 건가요?

2023-10-11 06:05 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/admin/dto/AdminPagingRequest.java
> +public record AdminPagingRequest(Long lastViewId, Integer limit) {
저희 다른 Paging 요청에서는 변수 이름이 `lastViewedId` 입니다!

2023-10-11 06:10 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/admin/presentation/AdminController.java
> +        session.setMaxInactiveInterval(3600);
여기서 세션 유지 시간을 1시간으로 정한 게 맞을까요?

만약 그렇다면, 도메인의 expiredDateTime 과 아주 살짝 차이가 날 수도 있겠군요! 재밌습니다.

SESSION, 3600 은 일부러 상수로 선언하지 않으신 건가요?

2023-10-11 06:11 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/common/config/AuthConfig.java
> +                .excludePathPatterns("/actuator/**")
actuator 안 써서 지워도 되지 않을까요?

2023-10-11 06:14 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/admin/application/PasswordEncoderTest.java
> +        // given
조사가 잘못됐네요. 비밀번호`가` 가 어떨까요?

2023-10-11 16:30 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/admin/dto/AdminPagingRequest.java
> +public record AdminPagingRequest(Long lastViewId, Integer limit) {
수정하겠습니다 👍

2023-10-11 16:31 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/common/config/AuthConfig.java
> +                .excludePathPatterns("/actuator/**")
후추의 pr에서 actuator 지우는 커밋을 저번에 봐서 제거하지 않았습니다!

2023-10-11 16:31 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/admin/application/AdminAuthService.java
> +        }
맛있.다!

2023-10-11 16:32 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/admin/application/AdminAuthServiceTest.java
> +    void 비밀번호를_5회_이상_틀리는_경우_예외가_발생한다() {
굳!

2023-10-11 16:36 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/admin/application/PasswordEncoderTest.java
> +        // given
수정 완료!

2023-10-11 16:38 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/admin/presentation/AdminController.java
> +        session.setMaxInactiveInterval(3600);
상수로 선언하는게 가독성이 더 좋겠네요! 수정했습니다.
도메인에 public 상수로 선언하고 재사용하려다 많은 부분이 재사용되지 않아 Controller에 상수 선언했습니다!

2023-10-11 16:39 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/admin/application/AdminService.java
> +    }
후추가 진행한 내용이랑 중복 작업이 될 것 같아서 일단 수정하지 않고, 추후에 화면 만들면서 수정하는 방향으로 진행해보겠습니다!

2023-10-12 01:33 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/admin/application/AdminService.java
> +    }
아하 좋습니다!

2023-10-12 01:34 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/admin/application/PasswordEncoder.java
> +    }
그야말로 Admin 이군요!

2023-10-12 01:35 UTC, Combi153 approved these changes
커멘트 답변 모두 확인했습니다

고생하셨습니다! 😃

2023-10-12 01:47 UTC, merged