[feat] 인수 테스트 작성 (#429)
woowacourse-teams/2023-trip-draw pull request #460
Opened 2023-10-10 08:24 UTC by greeng00se

### 📌 관련 이슈

- #429

### 📁 작업 설명

- 인수테스트보다 애플리케이션의 오류를 먼저 수정하기로 했습니다.
- 테스트 격리 수정한 내용은 선반영 하는건 어떨까요?

2023-10-11 02:44 UTC, Jaeyoung22 requested changes
고생하셨습니다! 커멘트 확인해주세요!

2023-10-11 02:44 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/test/ControllerTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
어노테이션 순서 이렇게 가는 것 맞나요?

2023-10-11 02:44 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/test/ControllerTest.java
> +)
@Sql을 제외하고 이걸 적용한 이유가 뭔가요?

2023-10-11 02:44 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/test/DatabaseCleaner.java
> +        return jdbcTemplate.queryForList(TRUNCATE_TABLE_QUERY, String.class);
왜 JDBCTemplate을 사용했나요?

2023-10-11 02:44 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/test/fixture/MemberFixture.java
> +        return new Member(1L, "통후추", "통후추", OauthType.KAKAO);
OAUTH 아이디라는 점을 알 수 있었으면 좋겠어요

2023-10-11 06:20 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/test/step/CommonStep.java
> +    }
이거 괜찮네요 👍

2023-10-11 06:21 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/trip/acceptance/TripAcceptanceTest.java
> +    }
인수테스트 전체를 한글로 했을 때 읽기 어렵다는 게 무슨 말인지 알 것 같네요. 너무 낯설군요.

2023-10-11 16:44 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/test/ControllerTest.java
> +)
테이블을 수정해도 sql 파일을 수정할 필요가 없어집니다!
[문서화](https://tripdraw.blog/spring-test-isolation) 해두었으니 확인해주세용~

2023-10-11 16:44 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/test/ControllerTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
순서 변경하겠습니당 ㅠㅠ

2023-10-11 16:45 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/test/DatabaseCleaner.java
> +        return jdbcTemplate.queryForList(TRUNCATE_TABLE_QUERY, String.class);
전체적으로 [해당 글](https://mangkyu.tistory.com/264)을 참고하면서 진행했고
EntityManager보단 단순하고 직관적이라고 생각합니다!

2023-10-11 16:47 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/trip/acceptance/TripAcceptanceTest.java
> +    }
기준을 세우고 점진적으로 추가하는 것이 좋아보입니다. 👍

2023-10-11 16:49 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/test/fixture/MemberFixture.java
> +        return new Member(1L, "통후추", "통후추", OauthType.KAKAO);
수정했습니다 👍

2023-10-13 08:04 UTC, Jaeyoung22 approved these changes
고생했습니다

2023-10-13 08:18 UTC, merged