[feat] 지역 조회 API 구현 (#493)
woowacourse-teams/2023-trip-draw pull request #509
Opened 2023-10-17 20:08 UTC by Jaeyoung22

### 📌 관련 이슈

- closed #493

### 📁 작업 설명

- 지역 조회 API를 구현했습니다.
- 초기에 데이터가 없을 시 행정구역을 모두 저장하는 API도 구현했습니다.

### 참고할 점
1. 현재 @Scheduled 어노테이션을 사용해서 매달 1일에 갱신하도록 했습니다.
2. 공공 API 중 단계별 행정구역 API 밖에 찾지 못하여, 현재 모든 행정구역을 저장하는 데까지 47초 정도 걸립니다. 추후 로직 변경(공공 API 변경 포함)과 비동기 처리 등으로 해결할 예정입니다.
3. @RestClientTest를 사용하여 RestTemplate을 mocking해서 테스트 진행했습니다. OpenAPIAreaService에서 진행했고, 이 클래스에 의존하는 AreaService에서는 이 클래스를 mocking 했습니다. AreaController에서는 테스트 작성을 하지 않았습니다.
4. 문서화는 빠른 시일내에 완료 후 공유하도록 하겠습니다. 궁금한 점은 커멘트로 남겨주세요.

2023-10-18 05:00 UTC, Combi153 requested changes
고생하셨습니다. 아프신데 몸조리 잘해서 얼른 나으세요 😢

2023-10-18 05:10 UTC, greeng00se requested changes
고생하셨습니다 Controller 부분 확인해주세용 나머지는 후추가 리뷰 잘 달아줬네요!

2023-10-18 05:10 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/area/presentation/AreaController.java
> +    public ResponseEntity<AreaResponse> read(@RequestBody AreaReqeust areaReqeust) {
RequestBody로 하면 안드로이드에서 요청이 안되야 수정해야 할 것 같습니당!

2023-10-18 05:10 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/area/presentation/AreaController.java
> +    }
추후에 어드민만 요청 가능하도록 변경해도 될 것 같아요!

2023-10-18 07:38 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/area/application/OpenAPIAreaService.java
> +@Transactional
분리했습니다! 감사합니다!

2023-10-18 07:57 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/area/dto/OpenAPIAreaResponse.java
> +        String longitude,
다른 response들은 json 내의 프로퍼티 이름이랑 필드 변수명이 일치하는데, 해당 클래스의 필드 변수명은 대응하지않아서 달아놨습니다! 통일하는게 나을까요?

2023-10-18 07:59 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/area/application/OpenAPIAreaService.java
> +public class OpenAPIAreaService {
변경해드렸숩니다^^

2023-10-18 08:00 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/area/application/AreaServiceTest.java
> +        when(openAPIAreaService.download()).thenReturn(
AreaServiceFacade를 사용하면서 mocking할 필요성이 없어졌네요! 감사합니다~

2023-10-18 08:00 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/area/application/AreaServiceTest.java
> +        verify(openAPIAreaService, times(1)).download();
AreaServiceFacade를 사용하면서 mocking할 필요성이 없어졌네요! 감사합니다~

2023-10-18 08:01 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/area/application/AreaService.java
> +    @Scheduled(cron = "0 0 0 1 * ?") // 매달 1일에 업데이트 한다는 CRON 표현식
Facade 패턴 도입으로 분리했습니다!

2023-10-18 08:01 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/area/application/AreaService.java
> +        List<Area> areas = openAPIAreaService.download();
Facade 패턴 도입으로 분리했습니다!

2023-10-18 08:01 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/area/application/AreaService.java
> +            AreaResponse.from(List.of());
앗 @Scheduled 를 설정하다가 놓쳐버렸네요..! 감사합니다!

2023-10-18 08:23 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/area/application/AreaService.java
> +        long count = areaRepository.count();
최대 3500건이라서 상관없을 것 같아요!

2023-10-18 08:24 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/area/application/AreaService.java
> +                .toList();
select distinct 쿼리를 날려도, 읍면동에 해당하는 칼럼의 데이터가 달라서 각각을 다 개별적인 row로 판단해서 기존의 쿼리랑 똑같은 결과가 나올 듯 합니다!
DTO로 각 칼럼의 데이터를 담아서 쏜다면 의미가 있겠지만 현재처럼 엔티티를 반환하는 형태에서는 더 효과적인 방법이 떠오르지 않네요ㅠㅠ 조금 더 고민해보겠습니다!

2023-10-18 08:45 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/area/presentation/AreaController.java
> +    public ResponseEntity<AreaResponse> read(@RequestBody AreaReqeust areaReqeust) {
변경했습니다!

2023-10-18 14:44 UTC, greeng00se approved these changes
크 고생하셨습니다 잘 돌아가네용! 👍

2023-10-19 01:50 UTC, Combi153 approved these changes
고생하셨습니다!
마지막까지 감사합니다

2023-10-19 02:04 UTC, merged