[fix] 인증 헤더 형식 변경 (#65)
woowacourse-teams/2023-trip-draw pull request #68
Opened 2023-07-24 08:54 UTC by Jaeyoung22

### 📌 관련 이슈

- closed #65 

### 📁 작업 설명

- 인증 헤더 형식이 잘못되었어서 변경했습니다.

2023-07-24 09:04 UTC, greeng00se requested changes
패키지 관련 코멘트 남겼습니다! 확인부탁드려요 👍

2023-07-24 09:04 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/presentation/member/Base64Decoder.java
> +import org.apache.tomcat.util.codec.binary.Base64;
java.util.Base64를 사용해보는 어떨까요 😄

2023-07-24 09:04 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/presentation/member/Base64Decoder.java
> +        return new String(decodedBytes);
Base64 decoder를 java.util.Base64 패키지에 있는 걸로 변경한 다음 예외 테스트 부탁드립니다 👍

2023-07-25 01:41 UTC, beer-2000 approved these changes
테스트에 명세서까지 잘 수정해주신 것 같습니다.
허브 리뷰만 반영하시고 머지하시면 될 것 같아 approve 남길게요.
고생하셨습니다!!

2023-07-25 01:41 UTC, beer-2000 commented on backend/src/main/java/dev/tripdraw/config/swagger/SwaggerLoginRequired.java
> +        description = "Authorization: BASE64(nickname) / default : 인코딩 된 \"통후추\"",
스웨거 수정까지 좋네용

2023-07-25 05:48 UTC, Combi153 approved these changes

2023-07-25 06:21 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/presentation/member/Base64Decoder.java
> +import org.apache.tomcat.util.codec.binary.Base64;
변경했습니다! 추가로 필요가 없어져서 Base64Decoder 클래스 삭제했습니다.

2023-07-25 06:21 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/presentation/member/Base64Decoder.java
> +        return new String(decodedBytes);
진행했습니다!

2023-07-25 06:22 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/config/swagger/SwaggerConfig.java
>          customHeader.schema(new StringSchema());
Basic 인증 방식이 {이메일}:{패스워드} 형식이 기본이라, 현재의 인증 방식이 Basic이 아니라는 판단 하에 변경했습니다!

2023-07-25 07:01 UTC, merged