Feature/#69
woowacourse-teams/2023-trip-draw pull request #89
Opened 2023-07-27 06:29 UTC by Jaeyoung22

### 📌 관련 이슈

- closed #69 

### 📁 작업 설명

- 특정 위치 정보 삭제 기능을 구현했습니다.

2023-07-27 07:12 UTC, beer-2000 requested changes
고생하셨습니다!
간단한 로직인데도 꼼꼼한 테스트를 작성하신 것이 인상적이었습니다.

몇 가지 질문 겸 제안 드렸으니 확인해주시고,
소통해주신 이후 확인하고 다시 approve 남기겠습니다.

2023-07-27 07:12 UTC, beer-2000 commented on backend/src/main/java/dev/tripdraw/exception/trip/TripExceptionType.java
> +    POINT_ALREADY_DELETED(CONFLICT, "이미 삭제된 위치정보입니다.");
혹시 다른 수정할 거 있으시면,
이것도 기존처럼
~~,
~~,
;
으로 돌려주실 수 있나요?

마지막 행에 콜론 없이 세미콜론만 있으면 복붙하다가 오타가 잘 나더라구요..!

2023-07-27 07:12 UTC, beer-2000 commented on backend/src/test/java/dev/tripdraw/application/TripServiceTest.java
> +    void 여행에서_위치정보를_삭제시_여행에_해당_위치정보가_존재하지_않으면_예외를_발생시킨다() {
꼼꼼한 테스트 너무 좋습니다!
다만 Route 내부에서 책임을 갖는 예외 POINT_NOT_FOUND에 대해서,
상위의 Trip, TripService 모두가 해당 예외 테스트를 하는 것이 꼭 필요할까라는 의문이 들었습니다.
꼼꼼한 테스트를 짜면 당연히 좋겠지만,
테스트 유지보수나 앞으로 추가할 테스트의 코드양이 많이 늘어날 수 있을 것 같아서요.

이 부분 의견이 궁금합니다!

2023-07-27 07:17 UTC, beer-2000 commented on backend/src/main/java/dev/tripdraw/application/TripService.java
> +    private Trip getByTripId(Long tripId) {
```suggestion
    private Trip findTripById(Long tripId) {
```
어떨지요?

2023-07-27 12:36 UTC, Combi153 reviewed
고생하셨습니다 리오!
궁금한 점, 논의할 만한 점 등을 코멘트로 남겨두었습니다. 확인 부탁드립니다.
화이팅 ~~!!

2023-07-27 15:27 UTC, greeng00se approved these changes
리뷰가 많이 늦어서 죄송합니다 🙇 
꼼꼼히 잘 구현해주신 것 같아요!
다른 분들이 꼼꼼하기 리뷰를 많이 남겨주셨기 때문에 제 코멘트는 참고만 해주세용~
일단 기능 구현이 우선이 되어야 할 것 같아서 저는 approve 하겠습니다~

2023-07-27 15:27 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/application/TripService.java
> +    private Trip getByTripId(Long tripId) {
저는 find의 경우 Spring Data와 혼동의 여지가 있어 보입니다. 메서드명은 지금도 괜찮다고 생각되네요.
다만 해당 메서드의 위치가 서비스에 있는 것은 고민을 좀 더 해보면 좋을 것 같습니다 👍 
물론 지금도 괜찮고, 추후에 리팩터링 하는 것도 좋을 것 같습니다.

2023-07-27 15:27 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/application/TripServiceTest.java
> +    void 여행에서_위치정보를_삭제시_여행에_해당_위치정보가_존재하지_않으면_예외를_발생시킨다() {
저는 시간만 있다면 꼼꼼히 작성하는 것도 좋지만 기준에 대해서는 4명이서 이야기를 해봐야할 것 같습니다 👍

2023-07-27 15:27 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
> +                .header("Authorization", 통후추_BASE64)
header 형식이 변경되어서 merge 전 확인 부탁드립니다.

2023-07-28 05:36 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/application/TripService.java
> +    public TripService(
앗 PointRepository 넣어보려다가 변경이 안됐네요 감사합니다!

2023-07-28 07:03 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/domain/trip/Route.java
> +                .filter(point -> Objects.equals(point.id(), pointId))
Objects.equals()가 null safe한 것으로 알고 있습니다. 
또, Long.equals()를 사용하면 인자로 들어가는 pointId가 (그럴리는 없겠지만) '123' 등의 형태로 들어올 때 Integer로 boxing 되는 것으로 알고 있습니다!

혹시 point.id().equals(pointId)로 사용했을 때의 장점을 알 수 있을까요?

2023-07-28 07:05 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/exception/trip/TripExceptionType.java
> +    POINT_ALREADY_DELETED(CONFLICT, "이미 삭제된 위치정보입니다.");
킹받네요... 죄송합니다!

2023-07-28 07:06 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/application/TripServiceTest.java
> +    void 여행에서_위치정보를_삭제시_여행에_해당_위치정보가_존재하지_않으면_예외를_발생시킨다() {
저는 꼼꼼한 것이 좋은 것 같아요~!

2023-07-28 07:10 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/application/TripService.java
> +    private Trip getByTripId(Long tripId) {
허브 의견에 동의합니다~~
혹시 근데 메서드의 위치가 서비스에 있는 것을 고민해야한다는 것이 TripRepository의 메서드와 거의 같은 역할을 하기 때문에 말씀하신 내용일까요?

2023-07-28 07:13 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/domain/trip/Point.java
> +
특별한 이유가 없이 포장 객체로 사용하긴 했습니다!
null이 가능하게 포장 객체로 사용하고 nullable을 false로 한 부분이 어색한 걸까요?

혹시 아니라면 해당 부분이 논리적이지 않은 부분에 대해서 조금 더 설명해주실 수 있을까요?

2023-07-28 07:14 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/domain/trip/Point.java
> +        }
동의합니다!
후에 조회 API에도 사용될 가능성이 높아보여서 분리하겠습니다! 좋은 의견 감사합니다!

2023-07-28 07:15 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/domain/trip/Route.java
> +    }
힙하다고 생각해서 이렇게 해봤는데... 분리하겠습니다!

2023-07-28 07:21 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/application/TripServiceTest.java
> +
저도 테스트 코드에 중복 코드가 많아서 리팩터링이 필요할 것으로 보입니다.
추후에 이슈를 발급하고 진행하는 것은 어떨까요?

2023-07-28 07:22 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/application/TripServiceTest.java
> +    }
맞네요! 감사합니다!

2023-07-28 07:23 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/domain/trip/RouteTest.java
> +    }
해당 point의 정보가 route의 메서드로 인해서 변경되었는지를 확인하는 메서드라고 생각했습니다. 그래서 기존에 있던 point를 사용했는데 이러한 논리는 어떻게 생각하실까요?

2023-07-28 07:25 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/domain/trip/RouteTest.java
> +    }
앗 복사 붙여넣기를 하다가 수정을 미처 다 못했네요! 감사합니다!

2023-07-28 07:28 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
> +        PointDeleteRequest pointDeleteRequest = new PointDeleteRequest(trip1.id(), pointResponse.pointId());
컨트롤러 테스트이다보니 컨트롤러에 존재하는 메서드로 진행을 해야한다고 생각합니다.
trip 도메인의 메서드가 오류가 생겼을 때 컨트롤러 테스트까지 영향을 받을 수 있을 것 같다고 생각하는데 혹시 이 부분은 어떻게 생각하실까요?

2023-07-28 07:28 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
> +        trip2 = tripRepository.save(Trip.from(member));
기존에 다른 방식으로 테스트를 진행하며 생성했었는데 로직이 변경된 후에 수정을 못했네요ㅠㅠ 감사합니다!

2023-07-28 07:37 UTC, beer-2000 commented on backend/src/main/java/dev/tripdraw/domain/trip/Route.java
> +                .filter(point -> Objects.equals(point.id(), pointId))
아하 null safe하다는 이점이 있군요 알려주셔서 감사합니다.
다른 장점은 없는 것 같습니다 ㅋㅋㅋ 기존대로 사용해주시면 감사하겠습니다.

2023-07-28 07:37 UTC, beer-2000 commented on backend/src/test/java/dev/tripdraw/application/TripServiceTest.java
> +    void 여행에서_위치정보를_삭제시_여행에_해당_위치정보가_존재하지_않으면_예외를_발생시킨다() {
넵넵 좋습니다~~
테스트 클래스가 너무 길어지기는 하나,
코드 작성하는 것은 (복붙하면돼서) 그리 오래 걸리지 않는 것 같아서
저도 동의합니다!

2023-07-28 07:40 UTC, beer-2000 approved these changes
코멘트 확인하고 답변 달았습니다~~
고생하셨습니다!

2023-07-28 07:42 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/application/TripServiceTest.java
> +    void 여행에서_위치정보를_삭제시_여행에_해당_위치정보가_존재하지_않으면_예외를_발생시킨다() {
엥? 테스트를 왜 두 번..

2023-07-28 07:58 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/domain/trip/Point.java
> +
말씀하신 부분이 맞습니다. `null이 가능하게 포장 객체를 사용한 것`과 `nullable = false 설정`이, 의도가 반대된다고 느껴졌습니다.

2023-07-28 08:04 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/domain/trip/Point.java
> +
제가 이해하기로는 필드의 자료형을 포장 객체로 하는 것은 비즈니스 로직을 진행할 때 null이 가능하게 하는 것이고,
column을 nullable false로 하는 것은 db에는 null을 허용하지 않게 하는 것이라고 알고 있습니다

비즈니스 로직을 진행하면서 (그럴리는 없겠지만) isDeleted가 null인 경우가 허용이 될 수도 있는데, db에는 그렇게 쌓이면 안되기 때문에 포장 객체를 사용해도 된다고 생각합니다.

id를 Long으로 사용하고 nullable=false를 하는 것과 비슷한 느낌으로 생각했습니다.
id가 null인 객체가 로직상에 존재할 수 있는데 db에는 있으면 안되는 느낌으로요..!

2023-07-28 08:06 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/domain/trip/Route.java
> +    }
ㅋㅋㅋㅋㅋㅋ힙하긴 합니다

2023-07-28 08:06 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/application/TripServiceTest.java
> +
좋습니다 한번 맞출 필요가 있을 것 같아요!

2023-07-28 08:11 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
> +        PointDeleteRequest pointDeleteRequest = new PointDeleteRequest(trip1.id(), pointResponse.pointId());
동의합니다. 그런데 제가 이렇게 짜다가 허브 엄마가 테스트 간결하게 하라고 해서 바꿨어요. 이것도 나중에 맞춰봅시다!

2023-07-28 08:35 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/domain/trip/RouteTest.java
> +    }
테스트 메서드명이 "경로에서 위치정보를 삭제한다" 입니다. 그러면 `경로 안에 있는 위치정보`가 삭제되었는지 여부를 검증해야 한다고 생각합니다.

따라서 경로 안에 있는 위치정보를 꺼내서 확인해야 합니다. 기존에 있던 point가 경로 안에 있는 위치정보와 완전히 동일한지 보장할 수 없기 때문입니다. 만약 route에서 point를 추가하거나 삭제할 때, 새로운 객체를 생성해 포함한다면(Point 객체가 불변이라면) 테스트가 실패할 것입니다.

더 넓은 범위에서 성공하는 테스트는 route에서 point를 꺼내서 검증하는 것이라 생각합니다. 리오의 생각은 어떠신가요?

2023-07-28 08:50 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/domain/trip/Point.java
> +
> 비즈니스 로직을 진행하면서 (그럴리는 없겠지만) isDeleted가 null인 경우가 허용이 될 수도 있는데

이 부분을 제가 생각 못했던 것 같습니다. 친절히 설명해주셔서 감사합니다!

2023-07-28 08:55 UTC, Combi153 approved these changes
모두 확인했습니다.
빠르고 친절하게 리뷰 반영해주셔서 감사합니다.
고생하셨습니다~!

2023-07-28 08:56 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/domain/trip/RouteTest.java
> +    }
추후 논의 해보기로 하고 일단 머지하겠습니다! 다같이 논의해보아요!

2023-07-28 08:57 UTC, merged