[feat] 여행 단일 조회 api 구현 및 여행 상태 필드(Enum) 추가 (#87)
woowacourse-teams/2023-trip-draw pull request #90
Opened 2023-07-27 07:42 UTC by Combi153

### 📌 관련 이슈

- closed #87 

### 📁 작업 설명

- 여행 단일 조회 api 및 테스트 추가했습니다.
- 여행 상태 관련 Enum Status 구현했습니다. (ONGOING, FINISHED)
- 여행에 상태를 나타내는 필드 Status status 추가했습니다.

2023-07-27 15:33 UTC, greeng00se reviewed
리뷰가 많이 늦었습니다 죄송합니다 🙇 
남아서 코딩하느라 고생하셨습니다.. 남긴 코멘트 참고 부탁드립니다~

2023-07-27 15:33 UTC, greeng00se commented on backend/src/main/java/dev/tripdraw/domain/trip/Status.java
> +    ONGOING, FINISHED
TripStatus로 닉변은 어떨까요? 다른 클래스도 Status와 유사한 형태로 사용한다면 혼동의 여지가 있을 것 같습니다~

2023-07-27 15:33 UTC, greeng00se commented on backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
> +                .header("Authorization", 통후추_BASE64)
merge 전 authorization 형식 변경에 관련해서 확인 부탁드립니다~

2023-07-28 00:56 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
> +                .header("Authorization", 통후추_BASE64)
넹 ~

2023-07-28 00:57 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/domain/trip/Status.java
> +    ONGOING, FINISHED
YAGNI 적용했습니다만, TripStatus로 해두면 나중에 편하겠네요

2023-07-28 00:57 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/application/TripService.java
> +    }
내가 먼저 했는데, 리오가 따라했어요

2023-07-28 02:43 UTC, greeng00se approved these changes
고생하셨습니다~

2023-07-28 03:18 UTC, beer-2000 requested changes
명세서와 동일한 스펙으로 잘 구현해주신 것 같습니다!
전반적으로 깔끔하게 수정해주셔서, 로직적인 수정은 필요 없다고 생각하고,
자잘한 것 관련해서 코멘트 남겼으니 반영 부탁드립니다!

확인 또는 반영해주시고 슬랙 멘션주시면 바로 approve 남기겠습니다.
감사합니다!

2023-07-28 03:18 UTC, beer-2000 commented on backend/src/main/java/dev/tripdraw/dto/trip/TripResponse.java
> +        @Schema(description = "여행 상태", example = "ONGOING")
설명에 ONGOING, FINISHED 가 들어갈 수 있다고 적어주면 좋을 것 같아요.
특히 이렇게 입력이 제한되는 경우에는 자세한 설명이 필요하다고 생각해서요!

2023-07-28 03:18 UTC, beer-2000 commented on backend/src/test/java/dev/tripdraw/application/TripServiceTest.java
> +    void trip_id로_여행을_조회한다() {
테스트 메서드 명에서, 전반적으로 객체의 이름을 한글로 표현했던 것 같아서요,
```suggestion
    void 여행을_ID로_조회한다() {
```
가 어떨지 제안드려봅니다.

2023-07-28 03:18 UTC, beer-2000 commented on backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
> +    void trip_id로_여행을_조회한다() {
서비스 테스트와 마찬가지로, 한글 클래스명을 테스트 메서드명에 사용하면 어떨까 싶습니다.
(물론 trip_id는 필드이긴 하지만요 ㅎㅎ)

2023-07-28 05:18 UTC, Combi153 commented on backend/src/main/java/dev/tripdraw/dto/trip/TripResponse.java
> +        @Schema(description = "여행 상태", example = "ONGOING")
동의합니다!
@Schema(description = "여행 상태 (option : ONGOING, FINISHED)", example = "ONGOING")
로 하면 이해하기 편할까요?

2023-07-28 05:19 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/application/TripServiceTest.java
> +    void trip_id로_여행을_조회한다() {
짚어주셔서 감사합니다 놓쳤던 부분이네요 👍

2023-07-28 05:20 UTC, Combi153 commented on backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
> +    void trip_id로_여행을_조회한다() {
동의합니다!

2023-07-28 05:27 UTC, Jaeyoung22 approved these changes
고생하셨습니다~~

2023-07-28 05:27 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/application/TripService.java
> +    }
저는 매우 동의합니다 다만 메서드명은 trip을 반환하는 것을 알 수 있게 하는 것은 어떨까요?

2023-07-28 05:27 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/application/TripService.java
> +    public TripResponse readById(LoginUser loginUser, Long id) {
해당 메서드도 trip을 반환하도록 하는 것이 좋을 것 같아요
현재 구조에서는 PointResponse도 TripService에서 날라가기 때문에 혼동의 여지가 있을 것 같아요~

2023-07-28 05:27 UTC, Jaeyoung22 commented on backend/src/test/java/dev/tripdraw/application/TripServiceTest.java
> +    void trip_id로_여행을_조회한다() {
동의합니다

2023-07-28 05:34 UTC, beer-2000 commented on backend/src/main/java/dev/tripdraw/dto/trip/TripResponse.java
> +        @Schema(description = "여행 상태", example = "ONGOING")
넵넵 좋습니다!

2023-07-28 05:35 UTC, beer-2000 approved these changes
리뷰 반영해주신 것 잘 확인했습니다~~
빠르게 반영해주셔서 감사드립니다.
고생하셨습니다!

2023-07-28 05:37 UTC, Jaeyoung22 requested changes
분리한 메서드명 변경에 대한 커멘트 남겨주시면 읽고 어프루브 하겠습니다!

2023-07-28 05:44 UTC, Jaeyoung22 requested changes

2023-07-28 05:44 UTC, Jaeyoung22 commented on backend/src/main/java/dev/tripdraw/application/TripService.java
> +    public TripResponse readTripById(LoginUser loginUser, Long id) {
여기 파라미터도 tripId로 통일하는 건 어떨까요?

2023-07-28 05:45 UTC, Jaeyoung22 approved these changes

2023-07-28 05:46 UTC, merged